// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Algorand.proto

package wallet.core.jni.proto;

public final class Algorand {
  private Algorand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TransferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Algorand.Proto.Transfer)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @return The toAddress.
     */
    java.lang.String getToAddress();
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @return The bytes for toAddress.
     */
    com.google.protobuf.ByteString
        getToAddressBytes();

    /**
     * <pre>
     * Amount
     * </pre>
     *
     * <code>uint64 amount = 2;</code>
     * @return The amount.
     */
    long getAmount();
  }
  /**
   * <pre>
   * Simple transfer message, transfer an amount to an address
   * </pre>
   *
   * Protobuf type {@code TW.Algorand.Proto.Transfer}
   */
  public  static final class Transfer extends
      com.google.protobuf.GeneratedMessageLite<
          Transfer, Transfer.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Algorand.Proto.Transfer)
      TransferOrBuilder {
    private Transfer() {
      toAddress_ = "";
    }
    public static final int TO_ADDRESS_FIELD_NUMBER = 1;
    private java.lang.String toAddress_;
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @return The toAddress.
     */
    @java.lang.Override
    public java.lang.String getToAddress() {
      return toAddress_;
    }
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @return The bytes for toAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToAddressBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(toAddress_);
    }
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @param value The toAddress to set.
     */
    private void setToAddress(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      toAddress_ = value;
    }
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     */
    private void clearToAddress() {
      
      toAddress_ = getDefaultInstance().getToAddress();
    }
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @param value The bytes for toAddress to set.
     */
    private void setToAddressBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      toAddress_ = value.toStringUtf8();
      
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private long amount_;
    /**
     * <pre>
     * Amount
     * </pre>
     *
     * <code>uint64 amount = 2;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * Amount
     * </pre>
     *
     * <code>uint64 amount = 2;</code>
     * @param value The amount to set.
     */
    private void setAmount(long value) {
      
      amount_ = value;
    }
    /**
     * <pre>
     * Amount
     * </pre>
     *
     * <code>uint64 amount = 2;</code>
     */
    private void clearAmount() {
      
      amount_ = 0L;
    }

    public static wallet.core.jni.proto.Algorand.Transfer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.Transfer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Algorand.Transfer prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Simple transfer message, transfer an amount to an address
     * </pre>
     *
     * Protobuf type {@code TW.Algorand.Proto.Transfer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Algorand.Transfer, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Algorand.Proto.Transfer)
        wallet.core.jni.proto.Algorand.TransferOrBuilder {
      // Construct using wallet.core.jni.proto.Algorand.Transfer.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Destination address (string)
       * </pre>
       *
       * <code>string to_address = 1;</code>
       * @return The toAddress.
       */
      @java.lang.Override
      public java.lang.String getToAddress() {
        return instance.getToAddress();
      }
      /**
       * <pre>
       * Destination address (string)
       * </pre>
       *
       * <code>string to_address = 1;</code>
       * @return The bytes for toAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getToAddressBytes() {
        return instance.getToAddressBytes();
      }
      /**
       * <pre>
       * Destination address (string)
       * </pre>
       *
       * <code>string to_address = 1;</code>
       * @param value The toAddress to set.
       * @return This builder for chaining.
       */
      public Builder setToAddress(
          java.lang.String value) {
        copyOnWrite();
        instance.setToAddress(value);
        return this;
      }
      /**
       * <pre>
       * Destination address (string)
       * </pre>
       *
       * <code>string to_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearToAddress() {
        copyOnWrite();
        instance.clearToAddress();
        return this;
      }
      /**
       * <pre>
       * Destination address (string)
       * </pre>
       *
       * <code>string to_address = 1;</code>
       * @param value The bytes for toAddress to set.
       * @return This builder for chaining.
       */
      public Builder setToAddressBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setToAddressBytes(value);
        return this;
      }

      /**
       * <pre>
       * Amount
       * </pre>
       *
       * <code>uint64 amount = 2;</code>
       * @return The amount.
       */
      @java.lang.Override
      public long getAmount() {
        return instance.getAmount();
      }
      /**
       * <pre>
       * Amount
       * </pre>
       *
       * <code>uint64 amount = 2;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(long value) {
        copyOnWrite();
        instance.setAmount(value);
        return this;
      }
      /**
       * <pre>
       * Amount
       * </pre>
       *
       * <code>uint64 amount = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        copyOnWrite();
        instance.clearAmount();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Algorand.Proto.Transfer)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Algorand.Transfer();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "toAddress_",
              "amount_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0003" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Algorand.Transfer> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Algorand.Transfer.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Algorand.Transfer>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Algorand.Proto.Transfer)
    private static final wallet.core.jni.proto.Algorand.Transfer DEFAULT_INSTANCE;
    static {
      Transfer defaultInstance = new Transfer();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Transfer.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Algorand.Transfer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Transfer> PARSER;

    public static com.google.protobuf.Parser<Transfer> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AssetTransferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Algorand.Proto.AssetTransfer)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @return The toAddress.
     */
    java.lang.String getToAddress();
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @return The bytes for toAddress.
     */
    com.google.protobuf.ByteString
        getToAddressBytes();

    /**
     * <pre>
     * Amount
     * </pre>
     *
     * <code>uint64 amount = 2;</code>
     * @return The amount.
     */
    long getAmount();

    /**
     * <pre>
     * ID of the asset being transferred
     * </pre>
     *
     * <code>uint64 asset_id = 3;</code>
     * @return The assetId.
     */
    long getAssetId();
  }
  /**
   * <pre>
   * Asset Transfer message, with assetID
   * </pre>
   *
   * Protobuf type {@code TW.Algorand.Proto.AssetTransfer}
   */
  public  static final class AssetTransfer extends
      com.google.protobuf.GeneratedMessageLite<
          AssetTransfer, AssetTransfer.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Algorand.Proto.AssetTransfer)
      AssetTransferOrBuilder {
    private AssetTransfer() {
      toAddress_ = "";
    }
    public static final int TO_ADDRESS_FIELD_NUMBER = 1;
    private java.lang.String toAddress_;
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @return The toAddress.
     */
    @java.lang.Override
    public java.lang.String getToAddress() {
      return toAddress_;
    }
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @return The bytes for toAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToAddressBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(toAddress_);
    }
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @param value The toAddress to set.
     */
    private void setToAddress(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      toAddress_ = value;
    }
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     */
    private void clearToAddress() {
      
      toAddress_ = getDefaultInstance().getToAddress();
    }
    /**
     * <pre>
     * Destination address (string)
     * </pre>
     *
     * <code>string to_address = 1;</code>
     * @param value The bytes for toAddress to set.
     */
    private void setToAddressBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      toAddress_ = value.toStringUtf8();
      
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private long amount_;
    /**
     * <pre>
     * Amount
     * </pre>
     *
     * <code>uint64 amount = 2;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * Amount
     * </pre>
     *
     * <code>uint64 amount = 2;</code>
     * @param value The amount to set.
     */
    private void setAmount(long value) {
      
      amount_ = value;
    }
    /**
     * <pre>
     * Amount
     * </pre>
     *
     * <code>uint64 amount = 2;</code>
     */
    private void clearAmount() {
      
      amount_ = 0L;
    }

    public static final int ASSET_ID_FIELD_NUMBER = 3;
    private long assetId_;
    /**
     * <pre>
     * ID of the asset being transferred
     * </pre>
     *
     * <code>uint64 asset_id = 3;</code>
     * @return The assetId.
     */
    @java.lang.Override
    public long getAssetId() {
      return assetId_;
    }
    /**
     * <pre>
     * ID of the asset being transferred
     * </pre>
     *
     * <code>uint64 asset_id = 3;</code>
     * @param value The assetId to set.
     */
    private void setAssetId(long value) {
      
      assetId_ = value;
    }
    /**
     * <pre>
     * ID of the asset being transferred
     * </pre>
     *
     * <code>uint64 asset_id = 3;</code>
     */
    private void clearAssetId() {
      
      assetId_ = 0L;
    }

    public static wallet.core.jni.proto.Algorand.AssetTransfer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.AssetTransfer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Algorand.AssetTransfer prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Asset Transfer message, with assetID
     * </pre>
     *
     * Protobuf type {@code TW.Algorand.Proto.AssetTransfer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Algorand.AssetTransfer, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Algorand.Proto.AssetTransfer)
        wallet.core.jni.proto.Algorand.AssetTransferOrBuilder {
      // Construct using wallet.core.jni.proto.Algorand.AssetTransfer.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Destination address (string)
       * </pre>
       *
       * <code>string to_address = 1;</code>
       * @return The toAddress.
       */
      @java.lang.Override
      public java.lang.String getToAddress() {
        return instance.getToAddress();
      }
      /**
       * <pre>
       * Destination address (string)
       * </pre>
       *
       * <code>string to_address = 1;</code>
       * @return The bytes for toAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getToAddressBytes() {
        return instance.getToAddressBytes();
      }
      /**
       * <pre>
       * Destination address (string)
       * </pre>
       *
       * <code>string to_address = 1;</code>
       * @param value The toAddress to set.
       * @return This builder for chaining.
       */
      public Builder setToAddress(
          java.lang.String value) {
        copyOnWrite();
        instance.setToAddress(value);
        return this;
      }
      /**
       * <pre>
       * Destination address (string)
       * </pre>
       *
       * <code>string to_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearToAddress() {
        copyOnWrite();
        instance.clearToAddress();
        return this;
      }
      /**
       * <pre>
       * Destination address (string)
       * </pre>
       *
       * <code>string to_address = 1;</code>
       * @param value The bytes for toAddress to set.
       * @return This builder for chaining.
       */
      public Builder setToAddressBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setToAddressBytes(value);
        return this;
      }

      /**
       * <pre>
       * Amount
       * </pre>
       *
       * <code>uint64 amount = 2;</code>
       * @return The amount.
       */
      @java.lang.Override
      public long getAmount() {
        return instance.getAmount();
      }
      /**
       * <pre>
       * Amount
       * </pre>
       *
       * <code>uint64 amount = 2;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(long value) {
        copyOnWrite();
        instance.setAmount(value);
        return this;
      }
      /**
       * <pre>
       * Amount
       * </pre>
       *
       * <code>uint64 amount = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        copyOnWrite();
        instance.clearAmount();
        return this;
      }

      /**
       * <pre>
       * ID of the asset being transferred
       * </pre>
       *
       * <code>uint64 asset_id = 3;</code>
       * @return The assetId.
       */
      @java.lang.Override
      public long getAssetId() {
        return instance.getAssetId();
      }
      /**
       * <pre>
       * ID of the asset being transferred
       * </pre>
       *
       * <code>uint64 asset_id = 3;</code>
       * @param value The assetId to set.
       * @return This builder for chaining.
       */
      public Builder setAssetId(long value) {
        copyOnWrite();
        instance.setAssetId(value);
        return this;
      }
      /**
       * <pre>
       * ID of the asset being transferred
       * </pre>
       *
       * <code>uint64 asset_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAssetId() {
        copyOnWrite();
        instance.clearAssetId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Algorand.Proto.AssetTransfer)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Algorand.AssetTransfer();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "toAddress_",
              "amount_",
              "assetId_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0003" +
                "\u0003\u0003";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Algorand.AssetTransfer> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Algorand.AssetTransfer.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Algorand.AssetTransfer>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Algorand.Proto.AssetTransfer)
    private static final wallet.core.jni.proto.Algorand.AssetTransfer DEFAULT_INSTANCE;
    static {
      AssetTransfer defaultInstance = new AssetTransfer();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AssetTransfer.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Algorand.AssetTransfer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AssetTransfer> PARSER;

    public static com.google.protobuf.Parser<AssetTransfer> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AssetOptInOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Algorand.Proto.AssetOptIn)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * ID of the asset
     * </pre>
     *
     * <code>uint64 asset_id = 1;</code>
     * @return The assetId.
     */
    long getAssetId();
  }
  /**
   * <pre>
   * Opt-in message for an asset
   * </pre>
   *
   * Protobuf type {@code TW.Algorand.Proto.AssetOptIn}
   */
  public  static final class AssetOptIn extends
      com.google.protobuf.GeneratedMessageLite<
          AssetOptIn, AssetOptIn.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Algorand.Proto.AssetOptIn)
      AssetOptInOrBuilder {
    private AssetOptIn() {
    }
    public static final int ASSET_ID_FIELD_NUMBER = 1;
    private long assetId_;
    /**
     * <pre>
     * ID of the asset
     * </pre>
     *
     * <code>uint64 asset_id = 1;</code>
     * @return The assetId.
     */
    @java.lang.Override
    public long getAssetId() {
      return assetId_;
    }
    /**
     * <pre>
     * ID of the asset
     * </pre>
     *
     * <code>uint64 asset_id = 1;</code>
     * @param value The assetId to set.
     */
    private void setAssetId(long value) {
      
      assetId_ = value;
    }
    /**
     * <pre>
     * ID of the asset
     * </pre>
     *
     * <code>uint64 asset_id = 1;</code>
     */
    private void clearAssetId() {
      
      assetId_ = 0L;
    }

    public static wallet.core.jni.proto.Algorand.AssetOptIn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.AssetOptIn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Algorand.AssetOptIn prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Opt-in message for an asset
     * </pre>
     *
     * Protobuf type {@code TW.Algorand.Proto.AssetOptIn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Algorand.AssetOptIn, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Algorand.Proto.AssetOptIn)
        wallet.core.jni.proto.Algorand.AssetOptInOrBuilder {
      // Construct using wallet.core.jni.proto.Algorand.AssetOptIn.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * ID of the asset
       * </pre>
       *
       * <code>uint64 asset_id = 1;</code>
       * @return The assetId.
       */
      @java.lang.Override
      public long getAssetId() {
        return instance.getAssetId();
      }
      /**
       * <pre>
       * ID of the asset
       * </pre>
       *
       * <code>uint64 asset_id = 1;</code>
       * @param value The assetId to set.
       * @return This builder for chaining.
       */
      public Builder setAssetId(long value) {
        copyOnWrite();
        instance.setAssetId(value);
        return this;
      }
      /**
       * <pre>
       * ID of the asset
       * </pre>
       *
       * <code>uint64 asset_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAssetId() {
        copyOnWrite();
        instance.clearAssetId();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Algorand.Proto.AssetOptIn)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Algorand.AssetOptIn();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "assetId_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0003";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Algorand.AssetOptIn> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Algorand.AssetOptIn.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Algorand.AssetOptIn>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Algorand.Proto.AssetOptIn)
    private static final wallet.core.jni.proto.Algorand.AssetOptIn DEFAULT_INSTANCE;
    static {
      AssetOptIn defaultInstance = new AssetOptIn();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AssetOptIn.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Algorand.AssetOptIn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AssetOptIn> PARSER;

    public static com.google.protobuf.Parser<AssetOptIn> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Algorand.Proto.SigningInput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * network / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     * @return The genesisId.
     */
    java.lang.String getGenesisId();
    /**
     * <pre>
     * network / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     * @return The bytes for genesisId.
     */
    com.google.protobuf.ByteString
        getGenesisIdBytes();

    /**
     * <pre>
     * network / chain hash
     * </pre>
     *
     * <code>bytes genesis_hash = 2;</code>
     * @return The genesisHash.
     */
    com.google.protobuf.ByteString getGenesisHash();

    /**
     * <pre>
     * binary note data
     * </pre>
     *
     * <code>bytes note = 3;</code>
     * @return The note.
     */
    com.google.protobuf.ByteString getNote();

    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 4;</code>
     * @return The privateKey.
     */
    com.google.protobuf.ByteString getPrivateKey();

    /**
     * <pre>
     * network / first round
     * </pre>
     *
     * <code>uint64 first_round = 5;</code>
     * @return The firstRound.
     */
    long getFirstRound();

    /**
     * <pre>
     * network / last round
     * </pre>
     *
     * <code>uint64 last_round = 6;</code>
     * @return The lastRound.
     */
    long getLastRound();

    /**
     * <pre>
     * fee amount
     * </pre>
     *
     * <code>uint64 fee = 7;</code>
     * @return The fee.
     */
    long getFee();

    /**
     * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
     * @return Whether the transfer field is set.
     */
    boolean hasTransfer();
    /**
     * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
     * @return The transfer.
     */
    wallet.core.jni.proto.Algorand.Transfer getTransfer();

    /**
     * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
     * @return Whether the assetTransfer field is set.
     */
    boolean hasAssetTransfer();
    /**
     * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
     * @return The assetTransfer.
     */
    wallet.core.jni.proto.Algorand.AssetTransfer getAssetTransfer();

    /**
     * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
     * @return Whether the assetOptIn field is set.
     */
    boolean hasAssetOptIn();
    /**
     * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
     * @return The assetOptIn.
     */
    wallet.core.jni.proto.Algorand.AssetOptIn getAssetOptIn();

    public wallet.core.jni.proto.Algorand.SigningInput.MessageOneofCase getMessageOneofCase();
  }
  /**
   * <pre>
   * Input data necessary to create a signed transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Algorand.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageLite<
          SigningInput, SigningInput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Algorand.Proto.SigningInput)
      SigningInputOrBuilder {
    private SigningInput() {
      genesisId_ = "";
      genesisHash_ = com.google.protobuf.ByteString.EMPTY;
      note_ = com.google.protobuf.ByteString.EMPTY;
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int messageOneofCase_ = 0;
    private java.lang.Object messageOneof_;
    public enum MessageOneofCase {
      TRANSFER(10),
      ASSET_TRANSFER(11),
      ASSET_OPT_IN(12),
      MESSAGEONEOF_NOT_SET(0);
      private final int value;
      private MessageOneofCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageOneofCase forNumber(int value) {
        switch (value) {
          case 10: return TRANSFER;
          case 11: return ASSET_TRANSFER;
          case 12: return ASSET_OPT_IN;
          case 0: return MESSAGEONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @java.lang.Override
    public MessageOneofCase
    getMessageOneofCase() {
      return MessageOneofCase.forNumber(
          messageOneofCase_);
    }

    private void clearMessageOneof() {
      messageOneofCase_ = 0;
      messageOneof_ = null;
    }

    public static final int GENESIS_ID_FIELD_NUMBER = 1;
    private java.lang.String genesisId_;
    /**
     * <pre>
     * network / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     * @return The genesisId.
     */
    @java.lang.Override
    public java.lang.String getGenesisId() {
      return genesisId_;
    }
    /**
     * <pre>
     * network / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     * @return The bytes for genesisId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGenesisIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(genesisId_);
    }
    /**
     * <pre>
     * network / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     * @param value The genesisId to set.
     */
    private void setGenesisId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      genesisId_ = value;
    }
    /**
     * <pre>
     * network / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     */
    private void clearGenesisId() {
      
      genesisId_ = getDefaultInstance().getGenesisId();
    }
    /**
     * <pre>
     * network / chain id
     * </pre>
     *
     * <code>string genesis_id = 1;</code>
     * @param value The bytes for genesisId to set.
     */
    private void setGenesisIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      genesisId_ = value.toStringUtf8();
      
    }

    public static final int GENESIS_HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString genesisHash_;
    /**
     * <pre>
     * network / chain hash
     * </pre>
     *
     * <code>bytes genesis_hash = 2;</code>
     * @return The genesisHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGenesisHash() {
      return genesisHash_;
    }
    /**
     * <pre>
     * network / chain hash
     * </pre>
     *
     * <code>bytes genesis_hash = 2;</code>
     * @param value The genesisHash to set.
     */
    private void setGenesisHash(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      genesisHash_ = value;
    }
    /**
     * <pre>
     * network / chain hash
     * </pre>
     *
     * <code>bytes genesis_hash = 2;</code>
     */
    private void clearGenesisHash() {
      
      genesisHash_ = getDefaultInstance().getGenesisHash();
    }

    public static final int NOTE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString note_;
    /**
     * <pre>
     * binary note data
     * </pre>
     *
     * <code>bytes note = 3;</code>
     * @return The note.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNote() {
      return note_;
    }
    /**
     * <pre>
     * binary note data
     * </pre>
     *
     * <code>bytes note = 3;</code>
     * @param value The note to set.
     */
    private void setNote(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      note_ = value;
    }
    /**
     * <pre>
     * binary note data
     * </pre>
     *
     * <code>bytes note = 3;</code>
     */
    private void clearNote() {
      
      note_ = getDefaultInstance().getNote();
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 4;</code>
     * @return The privateKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }
    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 4;</code>
     * @param value The privateKey to set.
     */
    private void setPrivateKey(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      privateKey_ = value;
    }
    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 4;</code>
     */
    private void clearPrivateKey() {
      
      privateKey_ = getDefaultInstance().getPrivateKey();
    }

    public static final int FIRST_ROUND_FIELD_NUMBER = 5;
    private long firstRound_;
    /**
     * <pre>
     * network / first round
     * </pre>
     *
     * <code>uint64 first_round = 5;</code>
     * @return The firstRound.
     */
    @java.lang.Override
    public long getFirstRound() {
      return firstRound_;
    }
    /**
     * <pre>
     * network / first round
     * </pre>
     *
     * <code>uint64 first_round = 5;</code>
     * @param value The firstRound to set.
     */
    private void setFirstRound(long value) {
      
      firstRound_ = value;
    }
    /**
     * <pre>
     * network / first round
     * </pre>
     *
     * <code>uint64 first_round = 5;</code>
     */
    private void clearFirstRound() {
      
      firstRound_ = 0L;
    }

    public static final int LAST_ROUND_FIELD_NUMBER = 6;
    private long lastRound_;
    /**
     * <pre>
     * network / last round
     * </pre>
     *
     * <code>uint64 last_round = 6;</code>
     * @return The lastRound.
     */
    @java.lang.Override
    public long getLastRound() {
      return lastRound_;
    }
    /**
     * <pre>
     * network / last round
     * </pre>
     *
     * <code>uint64 last_round = 6;</code>
     * @param value The lastRound to set.
     */
    private void setLastRound(long value) {
      
      lastRound_ = value;
    }
    /**
     * <pre>
     * network / last round
     * </pre>
     *
     * <code>uint64 last_round = 6;</code>
     */
    private void clearLastRound() {
      
      lastRound_ = 0L;
    }

    public static final int FEE_FIELD_NUMBER = 7;
    private long fee_;
    /**
     * <pre>
     * fee amount
     * </pre>
     *
     * <code>uint64 fee = 7;</code>
     * @return The fee.
     */
    @java.lang.Override
    public long getFee() {
      return fee_;
    }
    /**
     * <pre>
     * fee amount
     * </pre>
     *
     * <code>uint64 fee = 7;</code>
     * @param value The fee to set.
     */
    private void setFee(long value) {
      
      fee_ = value;
    }
    /**
     * <pre>
     * fee amount
     * </pre>
     *
     * <code>uint64 fee = 7;</code>
     */
    private void clearFee() {
      
      fee_ = 0L;
    }

    public static final int TRANSFER_FIELD_NUMBER = 10;
    /**
     * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
     */
    @java.lang.Override
    public boolean hasTransfer() {
      return messageOneofCase_ == 10;
    }
    /**
     * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
     */
    @java.lang.Override
    public wallet.core.jni.proto.Algorand.Transfer getTransfer() {
      if (messageOneofCase_ == 10) {
         return (wallet.core.jni.proto.Algorand.Transfer) messageOneof_;
      }
      return wallet.core.jni.proto.Algorand.Transfer.getDefaultInstance();
    }
    /**
     * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
     */
    private void setTransfer(wallet.core.jni.proto.Algorand.Transfer value) {
      value.getClass();
  messageOneof_ = value;
      messageOneofCase_ = 10;
    }
    /**
     * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
     */
    private void mergeTransfer(wallet.core.jni.proto.Algorand.Transfer value) {
      value.getClass();
  if (messageOneofCase_ == 10 &&
          messageOneof_ != wallet.core.jni.proto.Algorand.Transfer.getDefaultInstance()) {
        messageOneof_ = wallet.core.jni.proto.Algorand.Transfer.newBuilder((wallet.core.jni.proto.Algorand.Transfer) messageOneof_)
            .mergeFrom(value).buildPartial();
      } else {
        messageOneof_ = value;
      }
      messageOneofCase_ = 10;
    }
    /**
     * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
     */
    private void clearTransfer() {
      if (messageOneofCase_ == 10) {
        messageOneofCase_ = 0;
        messageOneof_ = null;
      }
    }

    public static final int ASSET_TRANSFER_FIELD_NUMBER = 11;
    /**
     * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
     */
    @java.lang.Override
    public boolean hasAssetTransfer() {
      return messageOneofCase_ == 11;
    }
    /**
     * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
     */
    @java.lang.Override
    public wallet.core.jni.proto.Algorand.AssetTransfer getAssetTransfer() {
      if (messageOneofCase_ == 11) {
         return (wallet.core.jni.proto.Algorand.AssetTransfer) messageOneof_;
      }
      return wallet.core.jni.proto.Algorand.AssetTransfer.getDefaultInstance();
    }
    /**
     * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
     */
    private void setAssetTransfer(wallet.core.jni.proto.Algorand.AssetTransfer value) {
      value.getClass();
  messageOneof_ = value;
      messageOneofCase_ = 11;
    }
    /**
     * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
     */
    private void mergeAssetTransfer(wallet.core.jni.proto.Algorand.AssetTransfer value) {
      value.getClass();
  if (messageOneofCase_ == 11 &&
          messageOneof_ != wallet.core.jni.proto.Algorand.AssetTransfer.getDefaultInstance()) {
        messageOneof_ = wallet.core.jni.proto.Algorand.AssetTransfer.newBuilder((wallet.core.jni.proto.Algorand.AssetTransfer) messageOneof_)
            .mergeFrom(value).buildPartial();
      } else {
        messageOneof_ = value;
      }
      messageOneofCase_ = 11;
    }
    /**
     * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
     */
    private void clearAssetTransfer() {
      if (messageOneofCase_ == 11) {
        messageOneofCase_ = 0;
        messageOneof_ = null;
      }
    }

    public static final int ASSET_OPT_IN_FIELD_NUMBER = 12;
    /**
     * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
     */
    @java.lang.Override
    public boolean hasAssetOptIn() {
      return messageOneofCase_ == 12;
    }
    /**
     * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
     */
    @java.lang.Override
    public wallet.core.jni.proto.Algorand.AssetOptIn getAssetOptIn() {
      if (messageOneofCase_ == 12) {
         return (wallet.core.jni.proto.Algorand.AssetOptIn) messageOneof_;
      }
      return wallet.core.jni.proto.Algorand.AssetOptIn.getDefaultInstance();
    }
    /**
     * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
     */
    private void setAssetOptIn(wallet.core.jni.proto.Algorand.AssetOptIn value) {
      value.getClass();
  messageOneof_ = value;
      messageOneofCase_ = 12;
    }
    /**
     * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
     */
    private void mergeAssetOptIn(wallet.core.jni.proto.Algorand.AssetOptIn value) {
      value.getClass();
  if (messageOneofCase_ == 12 &&
          messageOneof_ != wallet.core.jni.proto.Algorand.AssetOptIn.getDefaultInstance()) {
        messageOneof_ = wallet.core.jni.proto.Algorand.AssetOptIn.newBuilder((wallet.core.jni.proto.Algorand.AssetOptIn) messageOneof_)
            .mergeFrom(value).buildPartial();
      } else {
        messageOneof_ = value;
      }
      messageOneofCase_ = 12;
    }
    /**
     * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
     */
    private void clearAssetOptIn() {
      if (messageOneofCase_ == 12) {
        messageOneofCase_ = 0;
        messageOneof_ = null;
      }
    }

    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Algorand.SigningInput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Input data necessary to create a signed transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Algorand.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Algorand.SigningInput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Algorand.Proto.SigningInput)
        wallet.core.jni.proto.Algorand.SigningInputOrBuilder {
      // Construct using wallet.core.jni.proto.Algorand.SigningInput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public MessageOneofCase
          getMessageOneofCase() {
        return instance.getMessageOneofCase();
      }

      public Builder clearMessageOneof() {
        copyOnWrite();
        instance.clearMessageOneof();
        return this;
      }


      /**
       * <pre>
       * network / chain id
       * </pre>
       *
       * <code>string genesis_id = 1;</code>
       * @return The genesisId.
       */
      @java.lang.Override
      public java.lang.String getGenesisId() {
        return instance.getGenesisId();
      }
      /**
       * <pre>
       * network / chain id
       * </pre>
       *
       * <code>string genesis_id = 1;</code>
       * @return The bytes for genesisId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getGenesisIdBytes() {
        return instance.getGenesisIdBytes();
      }
      /**
       * <pre>
       * network / chain id
       * </pre>
       *
       * <code>string genesis_id = 1;</code>
       * @param value The genesisId to set.
       * @return This builder for chaining.
       */
      public Builder setGenesisId(
          java.lang.String value) {
        copyOnWrite();
        instance.setGenesisId(value);
        return this;
      }
      /**
       * <pre>
       * network / chain id
       * </pre>
       *
       * <code>string genesis_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGenesisId() {
        copyOnWrite();
        instance.clearGenesisId();
        return this;
      }
      /**
       * <pre>
       * network / chain id
       * </pre>
       *
       * <code>string genesis_id = 1;</code>
       * @param value The bytes for genesisId to set.
       * @return This builder for chaining.
       */
      public Builder setGenesisIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGenesisIdBytes(value);
        return this;
      }

      /**
       * <pre>
       * network / chain hash
       * </pre>
       *
       * <code>bytes genesis_hash = 2;</code>
       * @return The genesisHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGenesisHash() {
        return instance.getGenesisHash();
      }
      /**
       * <pre>
       * network / chain hash
       * </pre>
       *
       * <code>bytes genesis_hash = 2;</code>
       * @param value The genesisHash to set.
       * @return This builder for chaining.
       */
      public Builder setGenesisHash(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGenesisHash(value);
        return this;
      }
      /**
       * <pre>
       * network / chain hash
       * </pre>
       *
       * <code>bytes genesis_hash = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGenesisHash() {
        copyOnWrite();
        instance.clearGenesisHash();
        return this;
      }

      /**
       * <pre>
       * binary note data
       * </pre>
       *
       * <code>bytes note = 3;</code>
       * @return The note.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getNote() {
        return instance.getNote();
      }
      /**
       * <pre>
       * binary note data
       * </pre>
       *
       * <code>bytes note = 3;</code>
       * @param value The note to set.
       * @return This builder for chaining.
       */
      public Builder setNote(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNote(value);
        return this;
      }
      /**
       * <pre>
       * binary note data
       * </pre>
       *
       * <code>bytes note = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNote() {
        copyOnWrite();
        instance.clearNote();
        return this;
      }

      /**
       * <pre>
       * The secret private key used for signing (32 bytes).
       * </pre>
       *
       * <code>bytes private_key = 4;</code>
       * @return The privateKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPrivateKey() {
        return instance.getPrivateKey();
      }
      /**
       * <pre>
       * The secret private key used for signing (32 bytes).
       * </pre>
       *
       * <code>bytes private_key = 4;</code>
       * @param value The privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPrivateKey(value);
        return this;
      }
      /**
       * <pre>
       * The secret private key used for signing (32 bytes).
       * </pre>
       *
       * <code>bytes private_key = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKey() {
        copyOnWrite();
        instance.clearPrivateKey();
        return this;
      }

      /**
       * <pre>
       * network / first round
       * </pre>
       *
       * <code>uint64 first_round = 5;</code>
       * @return The firstRound.
       */
      @java.lang.Override
      public long getFirstRound() {
        return instance.getFirstRound();
      }
      /**
       * <pre>
       * network / first round
       * </pre>
       *
       * <code>uint64 first_round = 5;</code>
       * @param value The firstRound to set.
       * @return This builder for chaining.
       */
      public Builder setFirstRound(long value) {
        copyOnWrite();
        instance.setFirstRound(value);
        return this;
      }
      /**
       * <pre>
       * network / first round
       * </pre>
       *
       * <code>uint64 first_round = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstRound() {
        copyOnWrite();
        instance.clearFirstRound();
        return this;
      }

      /**
       * <pre>
       * network / last round
       * </pre>
       *
       * <code>uint64 last_round = 6;</code>
       * @return The lastRound.
       */
      @java.lang.Override
      public long getLastRound() {
        return instance.getLastRound();
      }
      /**
       * <pre>
       * network / last round
       * </pre>
       *
       * <code>uint64 last_round = 6;</code>
       * @param value The lastRound to set.
       * @return This builder for chaining.
       */
      public Builder setLastRound(long value) {
        copyOnWrite();
        instance.setLastRound(value);
        return this;
      }
      /**
       * <pre>
       * network / last round
       * </pre>
       *
       * <code>uint64 last_round = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastRound() {
        copyOnWrite();
        instance.clearLastRound();
        return this;
      }

      /**
       * <pre>
       * fee amount
       * </pre>
       *
       * <code>uint64 fee = 7;</code>
       * @return The fee.
       */
      @java.lang.Override
      public long getFee() {
        return instance.getFee();
      }
      /**
       * <pre>
       * fee amount
       * </pre>
       *
       * <code>uint64 fee = 7;</code>
       * @param value The fee to set.
       * @return This builder for chaining.
       */
      public Builder setFee(long value) {
        copyOnWrite();
        instance.setFee(value);
        return this;
      }
      /**
       * <pre>
       * fee amount
       * </pre>
       *
       * <code>uint64 fee = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFee() {
        copyOnWrite();
        instance.clearFee();
        return this;
      }

      /**
       * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
       */
      @java.lang.Override
      public boolean hasTransfer() {
        return instance.hasTransfer();
      }
      /**
       * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
       */
      @java.lang.Override
      public wallet.core.jni.proto.Algorand.Transfer getTransfer() {
        return instance.getTransfer();
      }
      /**
       * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
       */
      public Builder setTransfer(wallet.core.jni.proto.Algorand.Transfer value) {
        copyOnWrite();
        instance.setTransfer(value);
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
       */
      public Builder setTransfer(
          wallet.core.jni.proto.Algorand.Transfer.Builder builderForValue) {
        copyOnWrite();
        instance.setTransfer(builderForValue.build());
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
       */
      public Builder mergeTransfer(wallet.core.jni.proto.Algorand.Transfer value) {
        copyOnWrite();
        instance.mergeTransfer(value);
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.Transfer transfer = 10;</code>
       */
      public Builder clearTransfer() {
        copyOnWrite();
        instance.clearTransfer();
        return this;
      }

      /**
       * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
       */
      @java.lang.Override
      public boolean hasAssetTransfer() {
        return instance.hasAssetTransfer();
      }
      /**
       * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
       */
      @java.lang.Override
      public wallet.core.jni.proto.Algorand.AssetTransfer getAssetTransfer() {
        return instance.getAssetTransfer();
      }
      /**
       * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
       */
      public Builder setAssetTransfer(wallet.core.jni.proto.Algorand.AssetTransfer value) {
        copyOnWrite();
        instance.setAssetTransfer(value);
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
       */
      public Builder setAssetTransfer(
          wallet.core.jni.proto.Algorand.AssetTransfer.Builder builderForValue) {
        copyOnWrite();
        instance.setAssetTransfer(builderForValue.build());
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
       */
      public Builder mergeAssetTransfer(wallet.core.jni.proto.Algorand.AssetTransfer value) {
        copyOnWrite();
        instance.mergeAssetTransfer(value);
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.AssetTransfer asset_transfer = 11;</code>
       */
      public Builder clearAssetTransfer() {
        copyOnWrite();
        instance.clearAssetTransfer();
        return this;
      }

      /**
       * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
       */
      @java.lang.Override
      public boolean hasAssetOptIn() {
        return instance.hasAssetOptIn();
      }
      /**
       * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
       */
      @java.lang.Override
      public wallet.core.jni.proto.Algorand.AssetOptIn getAssetOptIn() {
        return instance.getAssetOptIn();
      }
      /**
       * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
       */
      public Builder setAssetOptIn(wallet.core.jni.proto.Algorand.AssetOptIn value) {
        copyOnWrite();
        instance.setAssetOptIn(value);
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
       */
      public Builder setAssetOptIn(
          wallet.core.jni.proto.Algorand.AssetOptIn.Builder builderForValue) {
        copyOnWrite();
        instance.setAssetOptIn(builderForValue.build());
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
       */
      public Builder mergeAssetOptIn(wallet.core.jni.proto.Algorand.AssetOptIn value) {
        copyOnWrite();
        instance.mergeAssetOptIn(value);
        return this;
      }
      /**
       * <code>.TW.Algorand.Proto.AssetOptIn asset_opt_in = 12;</code>
       */
      public Builder clearAssetOptIn() {
        copyOnWrite();
        instance.clearAssetOptIn();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Algorand.Proto.SigningInput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Algorand.SigningInput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "messageOneof_",
              "messageOneofCase_",
              "genesisId_",
              "genesisHash_",
              "note_",
              "privateKey_",
              "firstRound_",
              "lastRound_",
              "fee_",
              wallet.core.jni.proto.Algorand.Transfer.class,
              wallet.core.jni.proto.Algorand.AssetTransfer.class,
              wallet.core.jni.proto.Algorand.AssetOptIn.class,
            };
            java.lang.String info =
                "\u0000\n\u0001\u0000\u0001\f\n\u0000\u0000\u0000\u0001\u0208\u0002\n\u0003\n\u0004" +
                "\n\u0005\u0003\u0006\u0003\u0007\u0003\n<\u0000\u000b<\u0000\f<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Algorand.SigningInput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Algorand.SigningInput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Algorand.SigningInput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Algorand.Proto.SigningInput)
    private static final wallet.core.jni.proto.Algorand.SigningInput DEFAULT_INSTANCE;
    static {
      SigningInput defaultInstance = new SigningInput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SigningInput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Algorand.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningInput> PARSER;

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Algorand.Proto.SigningOutput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     * @return The encoded.
     */
    com.google.protobuf.ByteString getEncoded();
  }
  /**
   * <pre>
   * Result containing the signed and encoded transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Algorand.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageLite<
          SigningOutput, SigningOutput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Algorand.Proto.SigningOutput)
      SigningOutputOrBuilder {
    private SigningOutput() {
      encoded_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int ENCODED_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encoded_;
    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     * @return The encoded.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncoded() {
      return encoded_;
    }
    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     * @param value The encoded to set.
     */
    private void setEncoded(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      encoded_ = value;
    }
    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     */
    private void clearEncoded() {
      
      encoded_ = getDefaultInstance().getEncoded();
    }

    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Algorand.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Algorand.SigningOutput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Result containing the signed and encoded transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Algorand.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Algorand.SigningOutput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Algorand.Proto.SigningOutput)
        wallet.core.jni.proto.Algorand.SigningOutputOrBuilder {
      // Construct using wallet.core.jni.proto.Algorand.SigningOutput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       * @return The encoded.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncoded() {
        return instance.getEncoded();
      }
      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       * @param value The encoded to set.
       * @return This builder for chaining.
       */
      public Builder setEncoded(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEncoded(value);
        return this;
      }
      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncoded() {
        copyOnWrite();
        instance.clearEncoded();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Algorand.Proto.SigningOutput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Algorand.SigningOutput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "encoded_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Algorand.SigningOutput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Algorand.SigningOutput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Algorand.SigningOutput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Algorand.Proto.SigningOutput)
    private static final wallet.core.jni.proto.Algorand.SigningOutput DEFAULT_INSTANCE;
    static {
      SigningOutput defaultInstance = new SigningOutput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SigningOutput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Algorand.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningOutput> PARSER;

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
