// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfluxNetwork.proto

package wallet.core.jni.proto;

public final class ConfluxNetwork {
  private ConfluxNetwork() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.ConfluxNetwork.Proto.SigningInput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Chain identifier (256-bit number)
     * </pre>
     *
     * <code>bytes chain_id = 1;</code>
     * @return The chainId.
     */
    com.google.protobuf.ByteString getChainId();

    /**
     * <pre>
     * Nonce (256-bit number)
     * </pre>
     *
     * <code>bytes nonce = 2;</code>
     * @return The nonce.
     */
    com.google.protobuf.ByteString getNonce();

    /**
     * <pre>
     * Gas price (256-bit number)
     * </pre>
     *
     * <code>bytes gas_price = 3;</code>
     * @return The gasPrice.
     */
    com.google.protobuf.ByteString getGasPrice();

    /**
     * <pre>
     * Gas limit (256-bit number)
     * </pre>
     *
     * <code>bytes gas_limit = 4;</code>
     * @return The gasLimit.
     */
    com.google.protobuf.ByteString getGasLimit();

    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     * @return The toAddress.
     */
    java.lang.String getToAddress();
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     * @return The bytes for toAddress.
     */
    com.google.protobuf.ByteString
        getToAddressBytes();

    /**
     * <pre>
     * Amount to send in wei (256-bit number)
     * </pre>
     *
     * <code>bytes amount = 6;</code>
     * @return The amount.
     */
    com.google.protobuf.ByteString getAmount();

    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>bytes payload = 7;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();

    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 8;</code>
     * @return The privateKey.
     */
    com.google.protobuf.ByteString getPrivateKey();

    /**
     * <code>bytes storage_limit = 9;</code>
     * @return The storageLimit.
     */
    com.google.protobuf.ByteString getStorageLimit();

    /**
     * <code>bytes epoch_height = 10;</code>
     * @return The epochHeight.
     */
    com.google.protobuf.ByteString getEpochHeight();
  }
  /**
   * <pre>
   * Input data necessary to create a signed transaction.
   * </pre>
   *
   * Protobuf type {@code TW.ConfluxNetwork.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageLite<
          SigningInput, SigningInput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.ConfluxNetwork.Proto.SigningInput)
      SigningInputOrBuilder {
    private SigningInput() {
      chainId_ = com.google.protobuf.ByteString.EMPTY;
      nonce_ = com.google.protobuf.ByteString.EMPTY;
      gasPrice_ = com.google.protobuf.ByteString.EMPTY;
      gasLimit_ = com.google.protobuf.ByteString.EMPTY;
      toAddress_ = "";
      amount_ = com.google.protobuf.ByteString.EMPTY;
      payload_ = com.google.protobuf.ByteString.EMPTY;
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
      storageLimit_ = com.google.protobuf.ByteString.EMPTY;
      epochHeight_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int CHAIN_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString chainId_;
    /**
     * <pre>
     * Chain identifier (256-bit number)
     * </pre>
     *
     * <code>bytes chain_id = 1;</code>
     * @return The chainId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChainId() {
      return chainId_;
    }
    /**
     * <pre>
     * Chain identifier (256-bit number)
     * </pre>
     *
     * <code>bytes chain_id = 1;</code>
     * @param value The chainId to set.
     */
    private void setChainId(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      chainId_ = value;
    }
    /**
     * <pre>
     * Chain identifier (256-bit number)
     * </pre>
     *
     * <code>bytes chain_id = 1;</code>
     */
    private void clearChainId() {
      
      chainId_ = getDefaultInstance().getChainId();
    }

    public static final int NONCE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString nonce_;
    /**
     * <pre>
     * Nonce (256-bit number)
     * </pre>
     *
     * <code>bytes nonce = 2;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }
    /**
     * <pre>
     * Nonce (256-bit number)
     * </pre>
     *
     * <code>bytes nonce = 2;</code>
     * @param value The nonce to set.
     */
    private void setNonce(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      nonce_ = value;
    }
    /**
     * <pre>
     * Nonce (256-bit number)
     * </pre>
     *
     * <code>bytes nonce = 2;</code>
     */
    private void clearNonce() {
      
      nonce_ = getDefaultInstance().getNonce();
    }

    public static final int GAS_PRICE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString gasPrice_;
    /**
     * <pre>
     * Gas price (256-bit number)
     * </pre>
     *
     * <code>bytes gas_price = 3;</code>
     * @return The gasPrice.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGasPrice() {
      return gasPrice_;
    }
    /**
     * <pre>
     * Gas price (256-bit number)
     * </pre>
     *
     * <code>bytes gas_price = 3;</code>
     * @param value The gasPrice to set.
     */
    private void setGasPrice(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      gasPrice_ = value;
    }
    /**
     * <pre>
     * Gas price (256-bit number)
     * </pre>
     *
     * <code>bytes gas_price = 3;</code>
     */
    private void clearGasPrice() {
      
      gasPrice_ = getDefaultInstance().getGasPrice();
    }

    public static final int GAS_LIMIT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString gasLimit_;
    /**
     * <pre>
     * Gas limit (256-bit number)
     * </pre>
     *
     * <code>bytes gas_limit = 4;</code>
     * @return The gasLimit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGasLimit() {
      return gasLimit_;
    }
    /**
     * <pre>
     * Gas limit (256-bit number)
     * </pre>
     *
     * <code>bytes gas_limit = 4;</code>
     * @param value The gasLimit to set.
     */
    private void setGasLimit(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      gasLimit_ = value;
    }
    /**
     * <pre>
     * Gas limit (256-bit number)
     * </pre>
     *
     * <code>bytes gas_limit = 4;</code>
     */
    private void clearGasLimit() {
      
      gasLimit_ = getDefaultInstance().getGasLimit();
    }

    public static final int TO_ADDRESS_FIELD_NUMBER = 5;
    private java.lang.String toAddress_;
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     * @return The toAddress.
     */
    @java.lang.Override
    public java.lang.String getToAddress() {
      return toAddress_;
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     * @return The bytes for toAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToAddressBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(toAddress_);
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     * @param value The toAddress to set.
     */
    private void setToAddress(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      toAddress_ = value;
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     */
    private void clearToAddress() {
      
      toAddress_ = getDefaultInstance().getToAddress();
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 5;</code>
     * @param value The bytes for toAddress to set.
     */
    private void setToAddressBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      toAddress_ = value.toStringUtf8();
      
    }

    public static final int AMOUNT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString amount_;
    /**
     * <pre>
     * Amount to send in wei (256-bit number)
     * </pre>
     *
     * <code>bytes amount = 6;</code>
     * @return The amount.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * Amount to send in wei (256-bit number)
     * </pre>
     *
     * <code>bytes amount = 6;</code>
     * @param value The amount to set.
     */
    private void setAmount(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      amount_ = value;
    }
    /**
     * <pre>
     * Amount to send in wei (256-bit number)
     * </pre>
     *
     * <code>bytes amount = 6;</code>
     */
    private void clearAmount() {
      
      amount_ = getDefaultInstance().getAmount();
    }

    public static final int PAYLOAD_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString payload_;
    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>bytes payload = 7;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>bytes payload = 7;</code>
     * @param value The payload to set.
     */
    private void setPayload(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      payload_ = value;
    }
    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>bytes payload = 7;</code>
     */
    private void clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 8;</code>
     * @return The privateKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }
    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 8;</code>
     * @param value The privateKey to set.
     */
    private void setPrivateKey(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      privateKey_ = value;
    }
    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 8;</code>
     */
    private void clearPrivateKey() {
      
      privateKey_ = getDefaultInstance().getPrivateKey();
    }

    public static final int STORAGE_LIMIT_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString storageLimit_;
    /**
     * <code>bytes storage_limit = 9;</code>
     * @return The storageLimit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStorageLimit() {
      return storageLimit_;
    }
    /**
     * <code>bytes storage_limit = 9;</code>
     * @param value The storageLimit to set.
     */
    private void setStorageLimit(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      storageLimit_ = value;
    }
    /**
     * <code>bytes storage_limit = 9;</code>
     */
    private void clearStorageLimit() {
      
      storageLimit_ = getDefaultInstance().getStorageLimit();
    }

    public static final int EPOCH_HEIGHT_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString epochHeight_;
    /**
     * <code>bytes epoch_height = 10;</code>
     * @return The epochHeight.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEpochHeight() {
      return epochHeight_;
    }
    /**
     * <code>bytes epoch_height = 10;</code>
     * @param value The epochHeight to set.
     */
    private void setEpochHeight(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      epochHeight_ = value;
    }
    /**
     * <code>bytes epoch_height = 10;</code>
     */
    private void clearEpochHeight() {
      
      epochHeight_ = getDefaultInstance().getEpochHeight();
    }

    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.ConfluxNetwork.SigningInput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Input data necessary to create a signed transaction.
     * </pre>
     *
     * Protobuf type {@code TW.ConfluxNetwork.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.ConfluxNetwork.SigningInput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.ConfluxNetwork.Proto.SigningInput)
        wallet.core.jni.proto.ConfluxNetwork.SigningInputOrBuilder {
      // Construct using wallet.core.jni.proto.ConfluxNetwork.SigningInput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Chain identifier (256-bit number)
       * </pre>
       *
       * <code>bytes chain_id = 1;</code>
       * @return The chainId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChainId() {
        return instance.getChainId();
      }
      /**
       * <pre>
       * Chain identifier (256-bit number)
       * </pre>
       *
       * <code>bytes chain_id = 1;</code>
       * @param value The chainId to set.
       * @return This builder for chaining.
       */
      public Builder setChainId(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setChainId(value);
        return this;
      }
      /**
       * <pre>
       * Chain identifier (256-bit number)
       * </pre>
       *
       * <code>bytes chain_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearChainId() {
        copyOnWrite();
        instance.clearChainId();
        return this;
      }

      /**
       * <pre>
       * Nonce (256-bit number)
       * </pre>
       *
       * <code>bytes nonce = 2;</code>
       * @return The nonce.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getNonce() {
        return instance.getNonce();
      }
      /**
       * <pre>
       * Nonce (256-bit number)
       * </pre>
       *
       * <code>bytes nonce = 2;</code>
       * @param value The nonce to set.
       * @return This builder for chaining.
       */
      public Builder setNonce(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNonce(value);
        return this;
      }
      /**
       * <pre>
       * Nonce (256-bit number)
       * </pre>
       *
       * <code>bytes nonce = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonce() {
        copyOnWrite();
        instance.clearNonce();
        return this;
      }

      /**
       * <pre>
       * Gas price (256-bit number)
       * </pre>
       *
       * <code>bytes gas_price = 3;</code>
       * @return The gasPrice.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGasPrice() {
        return instance.getGasPrice();
      }
      /**
       * <pre>
       * Gas price (256-bit number)
       * </pre>
       *
       * <code>bytes gas_price = 3;</code>
       * @param value The gasPrice to set.
       * @return This builder for chaining.
       */
      public Builder setGasPrice(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGasPrice(value);
        return this;
      }
      /**
       * <pre>
       * Gas price (256-bit number)
       * </pre>
       *
       * <code>bytes gas_price = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasPrice() {
        copyOnWrite();
        instance.clearGasPrice();
        return this;
      }

      /**
       * <pre>
       * Gas limit (256-bit number)
       * </pre>
       *
       * <code>bytes gas_limit = 4;</code>
       * @return The gasLimit.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGasLimit() {
        return instance.getGasLimit();
      }
      /**
       * <pre>
       * Gas limit (256-bit number)
       * </pre>
       *
       * <code>bytes gas_limit = 4;</code>
       * @param value The gasLimit to set.
       * @return This builder for chaining.
       */
      public Builder setGasLimit(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGasLimit(value);
        return this;
      }
      /**
       * <pre>
       * Gas limit (256-bit number)
       * </pre>
       *
       * <code>bytes gas_limit = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasLimit() {
        copyOnWrite();
        instance.clearGasLimit();
        return this;
      }

      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 5;</code>
       * @return The toAddress.
       */
      @java.lang.Override
      public java.lang.String getToAddress() {
        return instance.getToAddress();
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 5;</code>
       * @return The bytes for toAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getToAddressBytes() {
        return instance.getToAddressBytes();
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 5;</code>
       * @param value The toAddress to set.
       * @return This builder for chaining.
       */
      public Builder setToAddress(
          java.lang.String value) {
        copyOnWrite();
        instance.setToAddress(value);
        return this;
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearToAddress() {
        copyOnWrite();
        instance.clearToAddress();
        return this;
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 5;</code>
       * @param value The bytes for toAddress to set.
       * @return This builder for chaining.
       */
      public Builder setToAddressBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setToAddressBytes(value);
        return this;
      }

      /**
       * <pre>
       * Amount to send in wei (256-bit number)
       * </pre>
       *
       * <code>bytes amount = 6;</code>
       * @return The amount.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAmount() {
        return instance.getAmount();
      }
      /**
       * <pre>
       * Amount to send in wei (256-bit number)
       * </pre>
       *
       * <code>bytes amount = 6;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAmount(value);
        return this;
      }
      /**
       * <pre>
       * Amount to send in wei (256-bit number)
       * </pre>
       *
       * <code>bytes amount = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        copyOnWrite();
        instance.clearAmount();
        return this;
      }

      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>bytes payload = 7;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return instance.getPayload();
      }
      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>bytes payload = 7;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPayload(value);
        return this;
      }
      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>bytes payload = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        copyOnWrite();
        instance.clearPayload();
        return this;
      }

      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 8;</code>
       * @return The privateKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPrivateKey() {
        return instance.getPrivateKey();
      }
      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 8;</code>
       * @param value The privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPrivateKey(value);
        return this;
      }
      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKey() {
        copyOnWrite();
        instance.clearPrivateKey();
        return this;
      }

      /**
       * <code>bytes storage_limit = 9;</code>
       * @return The storageLimit.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getStorageLimit() {
        return instance.getStorageLimit();
      }
      /**
       * <code>bytes storage_limit = 9;</code>
       * @param value The storageLimit to set.
       * @return This builder for chaining.
       */
      public Builder setStorageLimit(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setStorageLimit(value);
        return this;
      }
      /**
       * <code>bytes storage_limit = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearStorageLimit() {
        copyOnWrite();
        instance.clearStorageLimit();
        return this;
      }

      /**
       * <code>bytes epoch_height = 10;</code>
       * @return The epochHeight.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEpochHeight() {
        return instance.getEpochHeight();
      }
      /**
       * <code>bytes epoch_height = 10;</code>
       * @param value The epochHeight to set.
       * @return This builder for chaining.
       */
      public Builder setEpochHeight(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEpochHeight(value);
        return this;
      }
      /**
       * <code>bytes epoch_height = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearEpochHeight() {
        copyOnWrite();
        instance.clearEpochHeight();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.ConfluxNetwork.Proto.SigningInput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.ConfluxNetwork.SigningInput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "chainId_",
              "nonce_",
              "gasPrice_",
              "gasLimit_",
              "toAddress_",
              "amount_",
              "payload_",
              "privateKey_",
              "storageLimit_",
              "epochHeight_",
            };
            java.lang.String info =
                "\u0000\n\u0000\u0000\u0001\n\n\u0000\u0000\u0000\u0001\n\u0002\n\u0003\n\u0004\n" +
                "\u0005\u0208\u0006\n\u0007\n\b\n\t\n\n\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.ConfluxNetwork.SigningInput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.ConfluxNetwork.SigningInput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.ConfluxNetwork.SigningInput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.ConfluxNetwork.Proto.SigningInput)
    private static final wallet.core.jni.proto.ConfluxNetwork.SigningInput DEFAULT_INSTANCE;
    static {
      SigningInput defaultInstance = new SigningInput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SigningInput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.ConfluxNetwork.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningInput> PARSER;

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.ConfluxNetwork.Proto.SigningOutput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     * @return The encoded.
     */
    com.google.protobuf.ByteString getEncoded();

    /**
     * <code>bytes v = 2;</code>
     * @return The v.
     */
    com.google.protobuf.ByteString getV();

    /**
     * <code>bytes r = 3;</code>
     * @return The r.
     */
    com.google.protobuf.ByteString getR();

    /**
     * <code>bytes s = 4;</code>
     * @return The s.
     */
    com.google.protobuf.ByteString getS();
  }
  /**
   * <pre>
   * Transaction signing output.
   * </pre>
   *
   * Protobuf type {@code TW.ConfluxNetwork.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageLite<
          SigningOutput, SigningOutput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.ConfluxNetwork.Proto.SigningOutput)
      SigningOutputOrBuilder {
    private SigningOutput() {
      encoded_ = com.google.protobuf.ByteString.EMPTY;
      v_ = com.google.protobuf.ByteString.EMPTY;
      r_ = com.google.protobuf.ByteString.EMPTY;
      s_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int ENCODED_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString encoded_;
    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     * @return The encoded.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncoded() {
      return encoded_;
    }
    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     * @param value The encoded to set.
     */
    private void setEncoded(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      encoded_ = value;
    }
    /**
     * <pre>
     * Signed and encoded transaction bytes.
     * </pre>
     *
     * <code>bytes encoded = 1;</code>
     */
    private void clearEncoded() {
      
      encoded_ = getDefaultInstance().getEncoded();
    }

    public static final int V_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString v_;
    /**
     * <code>bytes v = 2;</code>
     * @return The v.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getV() {
      return v_;
    }
    /**
     * <code>bytes v = 2;</code>
     * @param value The v to set.
     */
    private void setV(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      v_ = value;
    }
    /**
     * <code>bytes v = 2;</code>
     */
    private void clearV() {
      
      v_ = getDefaultInstance().getV();
    }

    public static final int R_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString r_;
    /**
     * <code>bytes r = 3;</code>
     * @return The r.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getR() {
      return r_;
    }
    /**
     * <code>bytes r = 3;</code>
     * @param value The r to set.
     */
    private void setR(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      r_ = value;
    }
    /**
     * <code>bytes r = 3;</code>
     */
    private void clearR() {
      
      r_ = getDefaultInstance().getR();
    }

    public static final int S_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString s_;
    /**
     * <code>bytes s = 4;</code>
     * @return The s.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getS() {
      return s_;
    }
    /**
     * <code>bytes s = 4;</code>
     * @param value The s to set.
     */
    private void setS(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      s_ = value;
    }
    /**
     * <code>bytes s = 4;</code>
     */
    private void clearS() {
      
      s_ = getDefaultInstance().getS();
    }

    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.ConfluxNetwork.SigningOutput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Transaction signing output.
     * </pre>
     *
     * Protobuf type {@code TW.ConfluxNetwork.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.ConfluxNetwork.SigningOutput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.ConfluxNetwork.Proto.SigningOutput)
        wallet.core.jni.proto.ConfluxNetwork.SigningOutputOrBuilder {
      // Construct using wallet.core.jni.proto.ConfluxNetwork.SigningOutput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       * @return The encoded.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEncoded() {
        return instance.getEncoded();
      }
      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       * @param value The encoded to set.
       * @return This builder for chaining.
       */
      public Builder setEncoded(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEncoded(value);
        return this;
      }
      /**
       * <pre>
       * Signed and encoded transaction bytes.
       * </pre>
       *
       * <code>bytes encoded = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEncoded() {
        copyOnWrite();
        instance.clearEncoded();
        return this;
      }

      /**
       * <code>bytes v = 2;</code>
       * @return The v.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getV() {
        return instance.getV();
      }
      /**
       * <code>bytes v = 2;</code>
       * @param value The v to set.
       * @return This builder for chaining.
       */
      public Builder setV(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setV(value);
        return this;
      }
      /**
       * <code>bytes v = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearV() {
        copyOnWrite();
        instance.clearV();
        return this;
      }

      /**
       * <code>bytes r = 3;</code>
       * @return The r.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getR() {
        return instance.getR();
      }
      /**
       * <code>bytes r = 3;</code>
       * @param value The r to set.
       * @return This builder for chaining.
       */
      public Builder setR(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setR(value);
        return this;
      }
      /**
       * <code>bytes r = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearR() {
        copyOnWrite();
        instance.clearR();
        return this;
      }

      /**
       * <code>bytes s = 4;</code>
       * @return The s.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getS() {
        return instance.getS();
      }
      /**
       * <code>bytes s = 4;</code>
       * @param value The s to set.
       * @return This builder for chaining.
       */
      public Builder setS(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setS(value);
        return this;
      }
      /**
       * <code>bytes s = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearS() {
        copyOnWrite();
        instance.clearS();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.ConfluxNetwork.Proto.SigningOutput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.ConfluxNetwork.SigningOutput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "encoded_",
              "v_",
              "r_",
              "s_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\n\u0002\n\u0003" +
                "\n\u0004\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.ConfluxNetwork.SigningOutput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.ConfluxNetwork.SigningOutput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.ConfluxNetwork.SigningOutput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.ConfluxNetwork.Proto.SigningOutput)
    private static final wallet.core.jni.proto.ConfluxNetwork.SigningOutput DEFAULT_INSTANCE;
    static {
      SigningOutput defaultInstance = new SigningOutput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SigningOutput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.ConfluxNetwork.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningOutput> PARSER;

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
