// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mina.proto

package wallet.core.jni.proto;

public final class Mina {
  private Mina() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Mina.Proto.SigningInput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 1;</code>
     * @return The privateKey.
     */
    com.google.protobuf.ByteString getPrivateKey();

    /**
     * <pre>
     * Sender.
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The from.
     */
    java.lang.String getFrom();
    /**
     * <pre>
     * Sender.
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The bytes for from.
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <pre>
     * Receiver.
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The to.
     */
    java.lang.String getTo();
    /**
     * <pre>
     * Receiver.
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     * Amount to send.
     * </pre>
     *
     * <code>uint64 amount = 4;</code>
     * @return The amount.
     */
    long getAmount();

    /**
     * <pre>
     * Fee
     * </pre>
     *
     * <code>uint64 fee = 5;</code>
     * @return The fee.
     */
    long getFee();

    /**
     * <pre>
     * Nonce
     * </pre>
     *
     * <code>uint32 nonce = 6;</code>
     * @return The nonce.
     */
    int getNonce();

    /**
     * <pre>
     * Global Slot valid until
     * </pre>
     *
     * <code>uint64 valid_until = 7;</code>
     * @return The validUntil.
     */
    long getValidUntil();

    /**
     * <pre>
     * Memo
     * </pre>
     *
     * <code>string memo = 8;</code>
     * @return The memo.
     */
    java.lang.String getMemo();
    /**
     * <pre>
     * Memo
     * </pre>
     *
     * <code>string memo = 8;</code>
     * @return The bytes for memo.
     */
    com.google.protobuf.ByteString
        getMemoBytes();

    /**
     * <pre>
     * Delegation
     * </pre>
     *
     * <code>bool delegation = 9;</code>
     * @return The delegation.
     */
    boolean getDelegation();
  }
  /**
   * Protobuf type {@code TW.Mina.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageLite<
          SigningInput, SigningInput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Mina.Proto.SigningInput)
      SigningInputOrBuilder {
    private SigningInput() {
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
      from_ = "";
      to_ = "";
      memo_ = "";
    }
    public static final int PRIVATE_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 1;</code>
     * @return The privateKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }
    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 1;</code>
     * @param value The privateKey to set.
     */
    private void setPrivateKey(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      privateKey_ = value;
    }
    /**
     * <pre>
     * Private key.
     * </pre>
     *
     * <code>bytes private_key = 1;</code>
     */
    private void clearPrivateKey() {
      
      privateKey_ = getDefaultInstance().getPrivateKey();
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private java.lang.String from_;
    /**
     * <pre>
     * Sender.
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The from.
     */
    @java.lang.Override
    public java.lang.String getFrom() {
      return from_;
    }
    /**
     * <pre>
     * Sender.
     * </pre>
     *
     * <code>string from = 2;</code>
     * @return The bytes for from.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(from_);
    }
    /**
     * <pre>
     * Sender.
     * </pre>
     *
     * <code>string from = 2;</code>
     * @param value The from to set.
     */
    private void setFrom(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      from_ = value;
    }
    /**
     * <pre>
     * Sender.
     * </pre>
     *
     * <code>string from = 2;</code>
     */
    private void clearFrom() {
      
      from_ = getDefaultInstance().getFrom();
    }
    /**
     * <pre>
     * Sender.
     * </pre>
     *
     * <code>string from = 2;</code>
     * @param value The bytes for from to set.
     */
    private void setFromBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      from_ = value.toStringUtf8();
      
    }

    public static final int TO_FIELD_NUMBER = 3;
    private java.lang.String to_;
    /**
     * <pre>
     * Receiver.
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The to.
     */
    @java.lang.Override
    public java.lang.String getTo() {
      return to_;
    }
    /**
     * <pre>
     * Receiver.
     * </pre>
     *
     * <code>string to = 3;</code>
     * @return The bytes for to.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(to_);
    }
    /**
     * <pre>
     * Receiver.
     * </pre>
     *
     * <code>string to = 3;</code>
     * @param value The to to set.
     */
    private void setTo(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      to_ = value;
    }
    /**
     * <pre>
     * Receiver.
     * </pre>
     *
     * <code>string to = 3;</code>
     */
    private void clearTo() {
      
      to_ = getDefaultInstance().getTo();
    }
    /**
     * <pre>
     * Receiver.
     * </pre>
     *
     * <code>string to = 3;</code>
     * @param value The bytes for to to set.
     */
    private void setToBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      to_ = value.toStringUtf8();
      
    }

    public static final int AMOUNT_FIELD_NUMBER = 4;
    private long amount_;
    /**
     * <pre>
     * Amount to send.
     * </pre>
     *
     * <code>uint64 amount = 4;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * Amount to send.
     * </pre>
     *
     * <code>uint64 amount = 4;</code>
     * @param value The amount to set.
     */
    private void setAmount(long value) {
      
      amount_ = value;
    }
    /**
     * <pre>
     * Amount to send.
     * </pre>
     *
     * <code>uint64 amount = 4;</code>
     */
    private void clearAmount() {
      
      amount_ = 0L;
    }

    public static final int FEE_FIELD_NUMBER = 5;
    private long fee_;
    /**
     * <pre>
     * Fee
     * </pre>
     *
     * <code>uint64 fee = 5;</code>
     * @return The fee.
     */
    @java.lang.Override
    public long getFee() {
      return fee_;
    }
    /**
     * <pre>
     * Fee
     * </pre>
     *
     * <code>uint64 fee = 5;</code>
     * @param value The fee to set.
     */
    private void setFee(long value) {
      
      fee_ = value;
    }
    /**
     * <pre>
     * Fee
     * </pre>
     *
     * <code>uint64 fee = 5;</code>
     */
    private void clearFee() {
      
      fee_ = 0L;
    }

    public static final int NONCE_FIELD_NUMBER = 6;
    private int nonce_;
    /**
     * <pre>
     * Nonce
     * </pre>
     *
     * <code>uint32 nonce = 6;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public int getNonce() {
      return nonce_;
    }
    /**
     * <pre>
     * Nonce
     * </pre>
     *
     * <code>uint32 nonce = 6;</code>
     * @param value The nonce to set.
     */
    private void setNonce(int value) {
      
      nonce_ = value;
    }
    /**
     * <pre>
     * Nonce
     * </pre>
     *
     * <code>uint32 nonce = 6;</code>
     */
    private void clearNonce() {
      
      nonce_ = 0;
    }

    public static final int VALID_UNTIL_FIELD_NUMBER = 7;
    private long validUntil_;
    /**
     * <pre>
     * Global Slot valid until
     * </pre>
     *
     * <code>uint64 valid_until = 7;</code>
     * @return The validUntil.
     */
    @java.lang.Override
    public long getValidUntil() {
      return validUntil_;
    }
    /**
     * <pre>
     * Global Slot valid until
     * </pre>
     *
     * <code>uint64 valid_until = 7;</code>
     * @param value The validUntil to set.
     */
    private void setValidUntil(long value) {
      
      validUntil_ = value;
    }
    /**
     * <pre>
     * Global Slot valid until
     * </pre>
     *
     * <code>uint64 valid_until = 7;</code>
     */
    private void clearValidUntil() {
      
      validUntil_ = 0L;
    }

    public static final int MEMO_FIELD_NUMBER = 8;
    private java.lang.String memo_;
    /**
     * <pre>
     * Memo
     * </pre>
     *
     * <code>string memo = 8;</code>
     * @return The memo.
     */
    @java.lang.Override
    public java.lang.String getMemo() {
      return memo_;
    }
    /**
     * <pre>
     * Memo
     * </pre>
     *
     * <code>string memo = 8;</code>
     * @return The bytes for memo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMemoBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(memo_);
    }
    /**
     * <pre>
     * Memo
     * </pre>
     *
     * <code>string memo = 8;</code>
     * @param value The memo to set.
     */
    private void setMemo(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      memo_ = value;
    }
    /**
     * <pre>
     * Memo
     * </pre>
     *
     * <code>string memo = 8;</code>
     */
    private void clearMemo() {
      
      memo_ = getDefaultInstance().getMemo();
    }
    /**
     * <pre>
     * Memo
     * </pre>
     *
     * <code>string memo = 8;</code>
     * @param value The bytes for memo to set.
     */
    private void setMemoBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      memo_ = value.toStringUtf8();
      
    }

    public static final int DELEGATION_FIELD_NUMBER = 9;
    private boolean delegation_;
    /**
     * <pre>
     * Delegation
     * </pre>
     *
     * <code>bool delegation = 9;</code>
     * @return The delegation.
     */
    @java.lang.Override
    public boolean getDelegation() {
      return delegation_;
    }
    /**
     * <pre>
     * Delegation
     * </pre>
     *
     * <code>bool delegation = 9;</code>
     * @param value The delegation to set.
     */
    private void setDelegation(boolean value) {
      
      delegation_ = value;
    }
    /**
     * <pre>
     * Delegation
     * </pre>
     *
     * <code>bool delegation = 9;</code>
     */
    private void clearDelegation() {
      
      delegation_ = false;
    }

    public static wallet.core.jni.proto.Mina.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Mina.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Mina.SigningInput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code TW.Mina.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Mina.SigningInput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Mina.Proto.SigningInput)
        wallet.core.jni.proto.Mina.SigningInputOrBuilder {
      // Construct using wallet.core.jni.proto.Mina.SigningInput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 1;</code>
       * @return The privateKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPrivateKey() {
        return instance.getPrivateKey();
      }
      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 1;</code>
       * @param value The privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPrivateKey(value);
        return this;
      }
      /**
       * <pre>
       * Private key.
       * </pre>
       *
       * <code>bytes private_key = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKey() {
        copyOnWrite();
        instance.clearPrivateKey();
        return this;
      }

      /**
       * <pre>
       * Sender.
       * </pre>
       *
       * <code>string from = 2;</code>
       * @return The from.
       */
      @java.lang.Override
      public java.lang.String getFrom() {
        return instance.getFrom();
      }
      /**
       * <pre>
       * Sender.
       * </pre>
       *
       * <code>string from = 2;</code>
       * @return The bytes for from.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFromBytes() {
        return instance.getFromBytes();
      }
      /**
       * <pre>
       * Sender.
       * </pre>
       *
       * <code>string from = 2;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(
          java.lang.String value) {
        copyOnWrite();
        instance.setFrom(value);
        return this;
      }
      /**
       * <pre>
       * Sender.
       * </pre>
       *
       * <code>string from = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        copyOnWrite();
        instance.clearFrom();
        return this;
      }
      /**
       * <pre>
       * Sender.
       * </pre>
       *
       * <code>string from = 2;</code>
       * @param value The bytes for from to set.
       * @return This builder for chaining.
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFromBytes(value);
        return this;
      }

      /**
       * <pre>
       * Receiver.
       * </pre>
       *
       * <code>string to = 3;</code>
       * @return The to.
       */
      @java.lang.Override
      public java.lang.String getTo() {
        return instance.getTo();
      }
      /**
       * <pre>
       * Receiver.
       * </pre>
       *
       * <code>string to = 3;</code>
       * @return The bytes for to.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getToBytes() {
        return instance.getToBytes();
      }
      /**
       * <pre>
       * Receiver.
       * </pre>
       *
       * <code>string to = 3;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          java.lang.String value) {
        copyOnWrite();
        instance.setTo(value);
        return this;
      }
      /**
       * <pre>
       * Receiver.
       * </pre>
       *
       * <code>string to = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        copyOnWrite();
        instance.clearTo();
        return this;
      }
      /**
       * <pre>
       * Receiver.
       * </pre>
       *
       * <code>string to = 3;</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setToBytes(value);
        return this;
      }

      /**
       * <pre>
       * Amount to send.
       * </pre>
       *
       * <code>uint64 amount = 4;</code>
       * @return The amount.
       */
      @java.lang.Override
      public long getAmount() {
        return instance.getAmount();
      }
      /**
       * <pre>
       * Amount to send.
       * </pre>
       *
       * <code>uint64 amount = 4;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(long value) {
        copyOnWrite();
        instance.setAmount(value);
        return this;
      }
      /**
       * <pre>
       * Amount to send.
       * </pre>
       *
       * <code>uint64 amount = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        copyOnWrite();
        instance.clearAmount();
        return this;
      }

      /**
       * <pre>
       * Fee
       * </pre>
       *
       * <code>uint64 fee = 5;</code>
       * @return The fee.
       */
      @java.lang.Override
      public long getFee() {
        return instance.getFee();
      }
      /**
       * <pre>
       * Fee
       * </pre>
       *
       * <code>uint64 fee = 5;</code>
       * @param value The fee to set.
       * @return This builder for chaining.
       */
      public Builder setFee(long value) {
        copyOnWrite();
        instance.setFee(value);
        return this;
      }
      /**
       * <pre>
       * Fee
       * </pre>
       *
       * <code>uint64 fee = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFee() {
        copyOnWrite();
        instance.clearFee();
        return this;
      }

      /**
       * <pre>
       * Nonce
       * </pre>
       *
       * <code>uint32 nonce = 6;</code>
       * @return The nonce.
       */
      @java.lang.Override
      public int getNonce() {
        return instance.getNonce();
      }
      /**
       * <pre>
       * Nonce
       * </pre>
       *
       * <code>uint32 nonce = 6;</code>
       * @param value The nonce to set.
       * @return This builder for chaining.
       */
      public Builder setNonce(int value) {
        copyOnWrite();
        instance.setNonce(value);
        return this;
      }
      /**
       * <pre>
       * Nonce
       * </pre>
       *
       * <code>uint32 nonce = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonce() {
        copyOnWrite();
        instance.clearNonce();
        return this;
      }

      /**
       * <pre>
       * Global Slot valid until
       * </pre>
       *
       * <code>uint64 valid_until = 7;</code>
       * @return The validUntil.
       */
      @java.lang.Override
      public long getValidUntil() {
        return instance.getValidUntil();
      }
      /**
       * <pre>
       * Global Slot valid until
       * </pre>
       *
       * <code>uint64 valid_until = 7;</code>
       * @param value The validUntil to set.
       * @return This builder for chaining.
       */
      public Builder setValidUntil(long value) {
        copyOnWrite();
        instance.setValidUntil(value);
        return this;
      }
      /**
       * <pre>
       * Global Slot valid until
       * </pre>
       *
       * <code>uint64 valid_until = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearValidUntil() {
        copyOnWrite();
        instance.clearValidUntil();
        return this;
      }

      /**
       * <pre>
       * Memo
       * </pre>
       *
       * <code>string memo = 8;</code>
       * @return The memo.
       */
      @java.lang.Override
      public java.lang.String getMemo() {
        return instance.getMemo();
      }
      /**
       * <pre>
       * Memo
       * </pre>
       *
       * <code>string memo = 8;</code>
       * @return The bytes for memo.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMemoBytes() {
        return instance.getMemoBytes();
      }
      /**
       * <pre>
       * Memo
       * </pre>
       *
       * <code>string memo = 8;</code>
       * @param value The memo to set.
       * @return This builder for chaining.
       */
      public Builder setMemo(
          java.lang.String value) {
        copyOnWrite();
        instance.setMemo(value);
        return this;
      }
      /**
       * <pre>
       * Memo
       * </pre>
       *
       * <code>string memo = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemo() {
        copyOnWrite();
        instance.clearMemo();
        return this;
      }
      /**
       * <pre>
       * Memo
       * </pre>
       *
       * <code>string memo = 8;</code>
       * @param value The bytes for memo to set.
       * @return This builder for chaining.
       */
      public Builder setMemoBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMemoBytes(value);
        return this;
      }

      /**
       * <pre>
       * Delegation
       * </pre>
       *
       * <code>bool delegation = 9;</code>
       * @return The delegation.
       */
      @java.lang.Override
      public boolean getDelegation() {
        return instance.getDelegation();
      }
      /**
       * <pre>
       * Delegation
       * </pre>
       *
       * <code>bool delegation = 9;</code>
       * @param value The delegation to set.
       * @return This builder for chaining.
       */
      public Builder setDelegation(boolean value) {
        copyOnWrite();
        instance.setDelegation(value);
        return this;
      }
      /**
       * <pre>
       * Delegation
       * </pre>
       *
       * <code>bool delegation = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearDelegation() {
        copyOnWrite();
        instance.clearDelegation();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Mina.Proto.SigningInput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Mina.SigningInput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "privateKey_",
              "from_",
              "to_",
              "amount_",
              "fee_",
              "nonce_",
              "validUntil_",
              "memo_",
              "delegation_",
            };
            java.lang.String info =
                "\u0000\t\u0000\u0000\u0001\t\t\u0000\u0000\u0000\u0001\n\u0002\u0208\u0003\u0208" +
                "\u0004\u0003\u0005\u0003\u0006\u000b\u0007\u0003\b\u0208\t\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Mina.SigningInput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Mina.SigningInput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Mina.SigningInput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Mina.Proto.SigningInput)
    private static final wallet.core.jni.proto.Mina.SigningInput DEFAULT_INSTANCE;
    static {
      SigningInput defaultInstance = new SigningInput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SigningInput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Mina.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningInput> PARSER;

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Mina.Proto.SigningOutput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Signing output json.
     * </pre>
     *
     * <code>string json = 1;</code>
     * @return The json.
     */
    java.lang.String getJson();
    /**
     * <pre>
     * Signing output json.
     * </pre>
     *
     * <code>string json = 1;</code>
     * @return The bytes for json.
     */
    com.google.protobuf.ByteString
        getJsonBytes();

    /**
     * <pre>
     * Signature
     * </pre>
     *
     * <code>string signature = 2;</code>
     * @return The signature.
     */
    java.lang.String getSignature();
    /**
     * <pre>
     * Signature
     * </pre>
     *
     * <code>string signature = 2;</code>
     * @return The bytes for signature.
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <pre>
     * Optional error message.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @return The error.
     */
    java.lang.String getError();
    /**
     * <pre>
     * Optional error message.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @return The bytes for error.
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * <pre>
   * Transaction signing output.
   * </pre>
   *
   * Protobuf type {@code TW.Mina.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageLite<
          SigningOutput, SigningOutput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Mina.Proto.SigningOutput)
      SigningOutputOrBuilder {
    private SigningOutput() {
      json_ = "";
      signature_ = "";
      error_ = "";
    }
    public static final int JSON_FIELD_NUMBER = 1;
    private java.lang.String json_;
    /**
     * <pre>
     * Signing output json.
     * </pre>
     *
     * <code>string json = 1;</code>
     * @return The json.
     */
    @java.lang.Override
    public java.lang.String getJson() {
      return json_;
    }
    /**
     * <pre>
     * Signing output json.
     * </pre>
     *
     * <code>string json = 1;</code>
     * @return The bytes for json.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJsonBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(json_);
    }
    /**
     * <pre>
     * Signing output json.
     * </pre>
     *
     * <code>string json = 1;</code>
     * @param value The json to set.
     */
    private void setJson(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      json_ = value;
    }
    /**
     * <pre>
     * Signing output json.
     * </pre>
     *
     * <code>string json = 1;</code>
     */
    private void clearJson() {
      
      json_ = getDefaultInstance().getJson();
    }
    /**
     * <pre>
     * Signing output json.
     * </pre>
     *
     * <code>string json = 1;</code>
     * @param value The bytes for json to set.
     */
    private void setJsonBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      json_ = value.toStringUtf8();
      
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private java.lang.String signature_;
    /**
     * <pre>
     * Signature
     * </pre>
     *
     * <code>string signature = 2;</code>
     * @return The signature.
     */
    @java.lang.Override
    public java.lang.String getSignature() {
      return signature_;
    }
    /**
     * <pre>
     * Signature
     * </pre>
     *
     * <code>string signature = 2;</code>
     * @return The bytes for signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(signature_);
    }
    /**
     * <pre>
     * Signature
     * </pre>
     *
     * <code>string signature = 2;</code>
     * @param value The signature to set.
     */
    private void setSignature(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      signature_ = value;
    }
    /**
     * <pre>
     * Signature
     * </pre>
     *
     * <code>string signature = 2;</code>
     */
    private void clearSignature() {
      
      signature_ = getDefaultInstance().getSignature();
    }
    /**
     * <pre>
     * Signature
     * </pre>
     *
     * <code>string signature = 2;</code>
     * @param value The bytes for signature to set.
     */
    private void setSignatureBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      signature_ = value.toStringUtf8();
      
    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private java.lang.String error_;
    /**
     * <pre>
     * Optional error message.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @return The error.
     */
    @java.lang.Override
    public java.lang.String getError() {
      return error_;
    }
    /**
     * <pre>
     * Optional error message.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @return The bytes for error.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(error_);
    }
    /**
     * <pre>
     * Optional error message.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @param value The error to set.
     */
    private void setError(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      error_ = value;
    }
    /**
     * <pre>
     * Optional error message.
     * </pre>
     *
     * <code>string error = 3;</code>
     */
    private void clearError() {
      
      error_ = getDefaultInstance().getError();
    }
    /**
     * <pre>
     * Optional error message.
     * </pre>
     *
     * <code>string error = 3;</code>
     * @param value The bytes for error to set.
     */
    private void setErrorBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      error_ = value.toStringUtf8();
      
    }

    public static wallet.core.jni.proto.Mina.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Mina.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Mina.SigningOutput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Transaction signing output.
     * </pre>
     *
     * Protobuf type {@code TW.Mina.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Mina.SigningOutput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Mina.Proto.SigningOutput)
        wallet.core.jni.proto.Mina.SigningOutputOrBuilder {
      // Construct using wallet.core.jni.proto.Mina.SigningOutput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Signing output json.
       * </pre>
       *
       * <code>string json = 1;</code>
       * @return The json.
       */
      @java.lang.Override
      public java.lang.String getJson() {
        return instance.getJson();
      }
      /**
       * <pre>
       * Signing output json.
       * </pre>
       *
       * <code>string json = 1;</code>
       * @return The bytes for json.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getJsonBytes() {
        return instance.getJsonBytes();
      }
      /**
       * <pre>
       * Signing output json.
       * </pre>
       *
       * <code>string json = 1;</code>
       * @param value The json to set.
       * @return This builder for chaining.
       */
      public Builder setJson(
          java.lang.String value) {
        copyOnWrite();
        instance.setJson(value);
        return this;
      }
      /**
       * <pre>
       * Signing output json.
       * </pre>
       *
       * <code>string json = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJson() {
        copyOnWrite();
        instance.clearJson();
        return this;
      }
      /**
       * <pre>
       * Signing output json.
       * </pre>
       *
       * <code>string json = 1;</code>
       * @param value The bytes for json to set.
       * @return This builder for chaining.
       */
      public Builder setJsonBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setJsonBytes(value);
        return this;
      }

      /**
       * <pre>
       * Signature
       * </pre>
       *
       * <code>string signature = 2;</code>
       * @return The signature.
       */
      @java.lang.Override
      public java.lang.String getSignature() {
        return instance.getSignature();
      }
      /**
       * <pre>
       * Signature
       * </pre>
       *
       * <code>string signature = 2;</code>
       * @return The bytes for signature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        return instance.getSignatureBytes();
      }
      /**
       * <pre>
       * Signature
       * </pre>
       *
       * <code>string signature = 2;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(
          java.lang.String value) {
        copyOnWrite();
        instance.setSignature(value);
        return this;
      }
      /**
       * <pre>
       * Signature
       * </pre>
       *
       * <code>string signature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        copyOnWrite();
        instance.clearSignature();
        return this;
      }
      /**
       * <pre>
       * Signature
       * </pre>
       *
       * <code>string signature = 2;</code>
       * @param value The bytes for signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSignatureBytes(value);
        return this;
      }

      /**
       * <pre>
       * Optional error message.
       * </pre>
       *
       * <code>string error = 3;</code>
       * @return The error.
       */
      @java.lang.Override
      public java.lang.String getError() {
        return instance.getError();
      }
      /**
       * <pre>
       * Optional error message.
       * </pre>
       *
       * <code>string error = 3;</code>
       * @return The bytes for error.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getErrorBytes() {
        return instance.getErrorBytes();
      }
      /**
       * <pre>
       * Optional error message.
       * </pre>
       *
       * <code>string error = 3;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(
          java.lang.String value) {
        copyOnWrite();
        instance.setError(value);
        return this;
      }
      /**
       * <pre>
       * Optional error message.
       * </pre>
       *
       * <code>string error = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        copyOnWrite();
        instance.clearError();
        return this;
      }
      /**
       * <pre>
       * Optional error message.
       * </pre>
       *
       * <code>string error = 3;</code>
       * @param value The bytes for error to set.
       * @return This builder for chaining.
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrorBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Mina.Proto.SigningOutput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Mina.SigningOutput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "json_",
              "signature_",
              "error_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Mina.SigningOutput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Mina.SigningOutput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Mina.SigningOutput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Mina.Proto.SigningOutput)
    private static final wallet.core.jni.proto.Mina.SigningOutput DEFAULT_INSTANCE;
    static {
      SigningOutput defaultInstance = new SigningOutput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SigningOutput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Mina.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningOutput> PARSER;

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
