// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Nebulas.proto

package wallet.core.jni.proto;

public final class Nebulas {
  private Nebulas() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Nebulas.Proto.SigningInput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * sender's address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     * @return The fromAddress.
     */
    java.lang.String getFromAddress();
    /**
     * <pre>
     * sender's address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     * @return The bytes for fromAddress.
     */
    com.google.protobuf.ByteString
        getFromAddressBytes();

    /**
     * <pre>
     * Chain identifier (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes chain_id = 2;</code>
     * @return The chainId.
     */
    com.google.protobuf.ByteString getChainId();

    /**
     * <pre>
     * Nonce (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes nonce = 3;</code>
     * @return The nonce.
     */
    com.google.protobuf.ByteString getNonce();

    /**
     * <pre>
     * Gas price (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_price = 4;</code>
     * @return The gasPrice.
     */
    com.google.protobuf.ByteString getGasPrice();

    /**
     * <pre>
     * Gas limit (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_limit = 5;</code>
     * @return The gasLimit.
     */
    com.google.protobuf.ByteString getGasLimit();

    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 6;</code>
     * @return The toAddress.
     */
    java.lang.String getToAddress();
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 6;</code>
     * @return The bytes for toAddress.
     */
    com.google.protobuf.ByteString
        getToAddressBytes();

    /**
     * <pre>
     * Amount to send in wei, 1 NAS = 10^18 Wei (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes amount = 7;</code>
     * @return The amount.
     */
    com.google.protobuf.ByteString getAmount();

    /**
     * <pre>
     * Timestamp to create transaction (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes timestamp = 8;</code>
     * @return The timestamp.
     */
    com.google.protobuf.ByteString getTimestamp();

    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>string payload = 9;</code>
     * @return The payload.
     */
    java.lang.String getPayload();
    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>string payload = 9;</code>
     * @return The bytes for payload.
     */
    com.google.protobuf.ByteString
        getPayloadBytes();

    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 10;</code>
     * @return The privateKey.
     */
    com.google.protobuf.ByteString getPrivateKey();
  }
  /**
   * <pre>
   * Input data necessary to create a signed transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Nebulas.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageLite<
          SigningInput, SigningInput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Nebulas.Proto.SigningInput)
      SigningInputOrBuilder {
    private SigningInput() {
      fromAddress_ = "";
      chainId_ = com.google.protobuf.ByteString.EMPTY;
      nonce_ = com.google.protobuf.ByteString.EMPTY;
      gasPrice_ = com.google.protobuf.ByteString.EMPTY;
      gasLimit_ = com.google.protobuf.ByteString.EMPTY;
      toAddress_ = "";
      amount_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = com.google.protobuf.ByteString.EMPTY;
      payload_ = "";
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int FROM_ADDRESS_FIELD_NUMBER = 1;
    private java.lang.String fromAddress_;
    /**
     * <pre>
     * sender's address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     * @return The fromAddress.
     */
    @java.lang.Override
    public java.lang.String getFromAddress() {
      return fromAddress_;
    }
    /**
     * <pre>
     * sender's address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     * @return The bytes for fromAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFromAddressBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(fromAddress_);
    }
    /**
     * <pre>
     * sender's address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     * @param value The fromAddress to set.
     */
    private void setFromAddress(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      fromAddress_ = value;
    }
    /**
     * <pre>
     * sender's address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     */
    private void clearFromAddress() {
      
      fromAddress_ = getDefaultInstance().getFromAddress();
    }
    /**
     * <pre>
     * sender's address.
     * </pre>
     *
     * <code>string from_address = 1;</code>
     * @param value The bytes for fromAddress to set.
     */
    private void setFromAddressBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      fromAddress_ = value.toStringUtf8();
      
    }

    public static final int CHAIN_ID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString chainId_;
    /**
     * <pre>
     * Chain identifier (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes chain_id = 2;</code>
     * @return The chainId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getChainId() {
      return chainId_;
    }
    /**
     * <pre>
     * Chain identifier (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes chain_id = 2;</code>
     * @param value The chainId to set.
     */
    private void setChainId(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      chainId_ = value;
    }
    /**
     * <pre>
     * Chain identifier (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes chain_id = 2;</code>
     */
    private void clearChainId() {
      
      chainId_ = getDefaultInstance().getChainId();
    }

    public static final int NONCE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString nonce_;
    /**
     * <pre>
     * Nonce (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes nonce = 3;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return nonce_;
    }
    /**
     * <pre>
     * Nonce (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes nonce = 3;</code>
     * @param value The nonce to set.
     */
    private void setNonce(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      nonce_ = value;
    }
    /**
     * <pre>
     * Nonce (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes nonce = 3;</code>
     */
    private void clearNonce() {
      
      nonce_ = getDefaultInstance().getNonce();
    }

    public static final int GAS_PRICE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString gasPrice_;
    /**
     * <pre>
     * Gas price (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_price = 4;</code>
     * @return The gasPrice.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGasPrice() {
      return gasPrice_;
    }
    /**
     * <pre>
     * Gas price (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_price = 4;</code>
     * @param value The gasPrice to set.
     */
    private void setGasPrice(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      gasPrice_ = value;
    }
    /**
     * <pre>
     * Gas price (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_price = 4;</code>
     */
    private void clearGasPrice() {
      
      gasPrice_ = getDefaultInstance().getGasPrice();
    }

    public static final int GAS_LIMIT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString gasLimit_;
    /**
     * <pre>
     * Gas limit (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_limit = 5;</code>
     * @return The gasLimit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGasLimit() {
      return gasLimit_;
    }
    /**
     * <pre>
     * Gas limit (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_limit = 5;</code>
     * @param value The gasLimit to set.
     */
    private void setGasLimit(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      gasLimit_ = value;
    }
    /**
     * <pre>
     * Gas limit (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_limit = 5;</code>
     */
    private void clearGasLimit() {
      
      gasLimit_ = getDefaultInstance().getGasLimit();
    }

    public static final int TO_ADDRESS_FIELD_NUMBER = 6;
    private java.lang.String toAddress_;
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 6;</code>
     * @return The toAddress.
     */
    @java.lang.Override
    public java.lang.String getToAddress() {
      return toAddress_;
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 6;</code>
     * @return The bytes for toAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToAddressBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(toAddress_);
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 6;</code>
     * @param value The toAddress to set.
     */
    private void setToAddress(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      toAddress_ = value;
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 6;</code>
     */
    private void clearToAddress() {
      
      toAddress_ = getDefaultInstance().getToAddress();
    }
    /**
     * <pre>
     * Recipient's address.
     * </pre>
     *
     * <code>string to_address = 6;</code>
     * @param value The bytes for toAddress to set.
     */
    private void setToAddressBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      toAddress_ = value.toStringUtf8();
      
    }

    public static final int AMOUNT_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString amount_;
    /**
     * <pre>
     * Amount to send in wei, 1 NAS = 10^18 Wei (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes amount = 7;</code>
     * @return The amount.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * Amount to send in wei, 1 NAS = 10^18 Wei (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes amount = 7;</code>
     * @param value The amount to set.
     */
    private void setAmount(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      amount_ = value;
    }
    /**
     * <pre>
     * Amount to send in wei, 1 NAS = 10^18 Wei (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes amount = 7;</code>
     */
    private void clearAmount() {
      
      amount_ = getDefaultInstance().getAmount();
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString timestamp_;
    /**
     * <pre>
     * Timestamp to create transaction (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes timestamp = 8;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Timestamp to create transaction (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes timestamp = 8;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      timestamp_ = value;
    }
    /**
     * <pre>
     * Timestamp to create transaction (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes timestamp = 8;</code>
     */
    private void clearTimestamp() {
      
      timestamp_ = getDefaultInstance().getTimestamp();
    }

    public static final int PAYLOAD_FIELD_NUMBER = 9;
    private java.lang.String payload_;
    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>string payload = 9;</code>
     * @return The payload.
     */
    @java.lang.Override
    public java.lang.String getPayload() {
      return payload_;
    }
    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>string payload = 9;</code>
     * @return The bytes for payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(payload_);
    }
    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>string payload = 9;</code>
     * @param value The payload to set.
     */
    private void setPayload(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      payload_ = value;
    }
    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>string payload = 9;</code>
     */
    private void clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
    }
    /**
     * <pre>
     * Optional payload
     * </pre>
     *
     * <code>string payload = 9;</code>
     * @param value The bytes for payload to set.
     */
    private void setPayloadBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      payload_ = value.toStringUtf8();
      
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 10;</code>
     * @return The privateKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }
    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 10;</code>
     * @param value The privateKey to set.
     */
    private void setPrivateKey(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      privateKey_ = value;
    }
    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 10;</code>
     */
    private void clearPrivateKey() {
      
      privateKey_ = getDefaultInstance().getPrivateKey();
    }

    public static wallet.core.jni.proto.Nebulas.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Nebulas.SigningInput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Input data necessary to create a signed transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Nebulas.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Nebulas.SigningInput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Nebulas.Proto.SigningInput)
        wallet.core.jni.proto.Nebulas.SigningInputOrBuilder {
      // Construct using wallet.core.jni.proto.Nebulas.SigningInput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * sender's address.
       * </pre>
       *
       * <code>string from_address = 1;</code>
       * @return The fromAddress.
       */
      @java.lang.Override
      public java.lang.String getFromAddress() {
        return instance.getFromAddress();
      }
      /**
       * <pre>
       * sender's address.
       * </pre>
       *
       * <code>string from_address = 1;</code>
       * @return The bytes for fromAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFromAddressBytes() {
        return instance.getFromAddressBytes();
      }
      /**
       * <pre>
       * sender's address.
       * </pre>
       *
       * <code>string from_address = 1;</code>
       * @param value The fromAddress to set.
       * @return This builder for chaining.
       */
      public Builder setFromAddress(
          java.lang.String value) {
        copyOnWrite();
        instance.setFromAddress(value);
        return this;
      }
      /**
       * <pre>
       * sender's address.
       * </pre>
       *
       * <code>string from_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromAddress() {
        copyOnWrite();
        instance.clearFromAddress();
        return this;
      }
      /**
       * <pre>
       * sender's address.
       * </pre>
       *
       * <code>string from_address = 1;</code>
       * @param value The bytes for fromAddress to set.
       * @return This builder for chaining.
       */
      public Builder setFromAddressBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFromAddressBytes(value);
        return this;
      }

      /**
       * <pre>
       * Chain identifier (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes chain_id = 2;</code>
       * @return The chainId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getChainId() {
        return instance.getChainId();
      }
      /**
       * <pre>
       * Chain identifier (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes chain_id = 2;</code>
       * @param value The chainId to set.
       * @return This builder for chaining.
       */
      public Builder setChainId(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setChainId(value);
        return this;
      }
      /**
       * <pre>
       * Chain identifier (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes chain_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearChainId() {
        copyOnWrite();
        instance.clearChainId();
        return this;
      }

      /**
       * <pre>
       * Nonce (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes nonce = 3;</code>
       * @return The nonce.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getNonce() {
        return instance.getNonce();
      }
      /**
       * <pre>
       * Nonce (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes nonce = 3;</code>
       * @param value The nonce to set.
       * @return This builder for chaining.
       */
      public Builder setNonce(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNonce(value);
        return this;
      }
      /**
       * <pre>
       * Nonce (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes nonce = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonce() {
        copyOnWrite();
        instance.clearNonce();
        return this;
      }

      /**
       * <pre>
       * Gas price (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_price = 4;</code>
       * @return The gasPrice.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGasPrice() {
        return instance.getGasPrice();
      }
      /**
       * <pre>
       * Gas price (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_price = 4;</code>
       * @param value The gasPrice to set.
       * @return This builder for chaining.
       */
      public Builder setGasPrice(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGasPrice(value);
        return this;
      }
      /**
       * <pre>
       * Gas price (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_price = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasPrice() {
        copyOnWrite();
        instance.clearGasPrice();
        return this;
      }

      /**
       * <pre>
       * Gas limit (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_limit = 5;</code>
       * @return The gasLimit.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGasLimit() {
        return instance.getGasLimit();
      }
      /**
       * <pre>
       * Gas limit (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_limit = 5;</code>
       * @param value The gasLimit to set.
       * @return This builder for chaining.
       */
      public Builder setGasLimit(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGasLimit(value);
        return this;
      }
      /**
       * <pre>
       * Gas limit (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_limit = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasLimit() {
        copyOnWrite();
        instance.clearGasLimit();
        return this;
      }

      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 6;</code>
       * @return The toAddress.
       */
      @java.lang.Override
      public java.lang.String getToAddress() {
        return instance.getToAddress();
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 6;</code>
       * @return The bytes for toAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getToAddressBytes() {
        return instance.getToAddressBytes();
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 6;</code>
       * @param value The toAddress to set.
       * @return This builder for chaining.
       */
      public Builder setToAddress(
          java.lang.String value) {
        copyOnWrite();
        instance.setToAddress(value);
        return this;
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearToAddress() {
        copyOnWrite();
        instance.clearToAddress();
        return this;
      }
      /**
       * <pre>
       * Recipient's address.
       * </pre>
       *
       * <code>string to_address = 6;</code>
       * @param value The bytes for toAddress to set.
       * @return This builder for chaining.
       */
      public Builder setToAddressBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setToAddressBytes(value);
        return this;
      }

      /**
       * <pre>
       * Amount to send in wei, 1 NAS = 10^18 Wei (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes amount = 7;</code>
       * @return The amount.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAmount() {
        return instance.getAmount();
      }
      /**
       * <pre>
       * Amount to send in wei, 1 NAS = 10^18 Wei (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes amount = 7;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAmount(value);
        return this;
      }
      /**
       * <pre>
       * Amount to send in wei, 1 NAS = 10^18 Wei (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes amount = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        copyOnWrite();
        instance.clearAmount();
        return this;
      }

      /**
       * <pre>
       * Timestamp to create transaction (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes timestamp = 8;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * Timestamp to create transaction (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes timestamp = 8;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * Timestamp to create transaction (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes timestamp = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>string payload = 9;</code>
       * @return The payload.
       */
      @java.lang.Override
      public java.lang.String getPayload() {
        return instance.getPayload();
      }
      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>string payload = 9;</code>
       * @return The bytes for payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPayloadBytes() {
        return instance.getPayloadBytes();
      }
      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>string payload = 9;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(
          java.lang.String value) {
        copyOnWrite();
        instance.setPayload(value);
        return this;
      }
      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>string payload = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        copyOnWrite();
        instance.clearPayload();
        return this;
      }
      /**
       * <pre>
       * Optional payload
       * </pre>
       *
       * <code>string payload = 9;</code>
       * @param value The bytes for payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayloadBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPayloadBytes(value);
        return this;
      }

      /**
       * <pre>
       * The secret private key used for signing (32 bytes).
       * </pre>
       *
       * <code>bytes private_key = 10;</code>
       * @return The privateKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPrivateKey() {
        return instance.getPrivateKey();
      }
      /**
       * <pre>
       * The secret private key used for signing (32 bytes).
       * </pre>
       *
       * <code>bytes private_key = 10;</code>
       * @param value The privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPrivateKey(value);
        return this;
      }
      /**
       * <pre>
       * The secret private key used for signing (32 bytes).
       * </pre>
       *
       * <code>bytes private_key = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKey() {
        copyOnWrite();
        instance.clearPrivateKey();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Nebulas.Proto.SigningInput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Nebulas.SigningInput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "fromAddress_",
              "chainId_",
              "nonce_",
              "gasPrice_",
              "gasLimit_",
              "toAddress_",
              "amount_",
              "timestamp_",
              "payload_",
              "privateKey_",
            };
            java.lang.String info =
                "\u0000\n\u0000\u0000\u0001\n\n\u0000\u0000\u0000\u0001\u0208\u0002\n\u0003\n\u0004" +
                "\n\u0005\n\u0006\u0208\u0007\n\b\n\t\u0208\n\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Nebulas.SigningInput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Nebulas.SigningInput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Nebulas.SigningInput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Nebulas.Proto.SigningInput)
    private static final wallet.core.jni.proto.Nebulas.SigningInput DEFAULT_INSTANCE;
    static {
      SigningInput defaultInstance = new SigningInput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SigningInput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Nebulas.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningInput> PARSER;

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Nebulas.Proto.SigningOutput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Algorithm code
     * </pre>
     *
     * <code>uint32 algorithm = 1;</code>
     * @return The algorithm.
     */
    int getAlgorithm();

    /**
     * <pre>
     * The signature
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <pre>
     * Encoded transaction
     * </pre>
     *
     * <code>string raw = 3;</code>
     * @return The raw.
     */
    java.lang.String getRaw();
    /**
     * <pre>
     * Encoded transaction
     * </pre>
     *
     * <code>string raw = 3;</code>
     * @return The bytes for raw.
     */
    com.google.protobuf.ByteString
        getRawBytes();
  }
  /**
   * <pre>
   * Result containing the signed and encoded transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Nebulas.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageLite<
          SigningOutput, SigningOutput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Nebulas.Proto.SigningOutput)
      SigningOutputOrBuilder {
    private SigningOutput() {
      signature_ = com.google.protobuf.ByteString.EMPTY;
      raw_ = "";
    }
    public static final int ALGORITHM_FIELD_NUMBER = 1;
    private int algorithm_;
    /**
     * <pre>
     * Algorithm code
     * </pre>
     *
     * <code>uint32 algorithm = 1;</code>
     * @return The algorithm.
     */
    @java.lang.Override
    public int getAlgorithm() {
      return algorithm_;
    }
    /**
     * <pre>
     * Algorithm code
     * </pre>
     *
     * <code>uint32 algorithm = 1;</code>
     * @param value The algorithm to set.
     */
    private void setAlgorithm(int value) {
      
      algorithm_ = value;
    }
    /**
     * <pre>
     * Algorithm code
     * </pre>
     *
     * <code>uint32 algorithm = 1;</code>
     */
    private void clearAlgorithm() {
      
      algorithm_ = 0;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <pre>
     * The signature
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <pre>
     * The signature
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     * @param value The signature to set.
     */
    private void setSignature(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      signature_ = value;
    }
    /**
     * <pre>
     * The signature
     * </pre>
     *
     * <code>bytes signature = 2;</code>
     */
    private void clearSignature() {
      
      signature_ = getDefaultInstance().getSignature();
    }

    public static final int RAW_FIELD_NUMBER = 3;
    private java.lang.String raw_;
    /**
     * <pre>
     * Encoded transaction
     * </pre>
     *
     * <code>string raw = 3;</code>
     * @return The raw.
     */
    @java.lang.Override
    public java.lang.String getRaw() {
      return raw_;
    }
    /**
     * <pre>
     * Encoded transaction
     * </pre>
     *
     * <code>string raw = 3;</code>
     * @return The bytes for raw.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRawBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(raw_);
    }
    /**
     * <pre>
     * Encoded transaction
     * </pre>
     *
     * <code>string raw = 3;</code>
     * @param value The raw to set.
     */
    private void setRaw(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      raw_ = value;
    }
    /**
     * <pre>
     * Encoded transaction
     * </pre>
     *
     * <code>string raw = 3;</code>
     */
    private void clearRaw() {
      
      raw_ = getDefaultInstance().getRaw();
    }
    /**
     * <pre>
     * Encoded transaction
     * </pre>
     *
     * <code>string raw = 3;</code>
     * @param value The bytes for raw to set.
     */
    private void setRawBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      raw_ = value.toStringUtf8();
      
    }

    public static wallet.core.jni.proto.Nebulas.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Nebulas.SigningOutput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Result containing the signed and encoded transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Nebulas.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Nebulas.SigningOutput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Nebulas.Proto.SigningOutput)
        wallet.core.jni.proto.Nebulas.SigningOutputOrBuilder {
      // Construct using wallet.core.jni.proto.Nebulas.SigningOutput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Algorithm code
       * </pre>
       *
       * <code>uint32 algorithm = 1;</code>
       * @return The algorithm.
       */
      @java.lang.Override
      public int getAlgorithm() {
        return instance.getAlgorithm();
      }
      /**
       * <pre>
       * Algorithm code
       * </pre>
       *
       * <code>uint32 algorithm = 1;</code>
       * @param value The algorithm to set.
       * @return This builder for chaining.
       */
      public Builder setAlgorithm(int value) {
        copyOnWrite();
        instance.setAlgorithm(value);
        return this;
      }
      /**
       * <pre>
       * Algorithm code
       * </pre>
       *
       * <code>uint32 algorithm = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlgorithm() {
        copyOnWrite();
        instance.clearAlgorithm();
        return this;
      }

      /**
       * <pre>
       * The signature
       * </pre>
       *
       * <code>bytes signature = 2;</code>
       * @return The signature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSignature() {
        return instance.getSignature();
      }
      /**
       * <pre>
       * The signature
       * </pre>
       *
       * <code>bytes signature = 2;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSignature(value);
        return this;
      }
      /**
       * <pre>
       * The signature
       * </pre>
       *
       * <code>bytes signature = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        copyOnWrite();
        instance.clearSignature();
        return this;
      }

      /**
       * <pre>
       * Encoded transaction
       * </pre>
       *
       * <code>string raw = 3;</code>
       * @return The raw.
       */
      @java.lang.Override
      public java.lang.String getRaw() {
        return instance.getRaw();
      }
      /**
       * <pre>
       * Encoded transaction
       * </pre>
       *
       * <code>string raw = 3;</code>
       * @return The bytes for raw.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getRawBytes() {
        return instance.getRawBytes();
      }
      /**
       * <pre>
       * Encoded transaction
       * </pre>
       *
       * <code>string raw = 3;</code>
       * @param value The raw to set.
       * @return This builder for chaining.
       */
      public Builder setRaw(
          java.lang.String value) {
        copyOnWrite();
        instance.setRaw(value);
        return this;
      }
      /**
       * <pre>
       * Encoded transaction
       * </pre>
       *
       * <code>string raw = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRaw() {
        copyOnWrite();
        instance.clearRaw();
        return this;
      }
      /**
       * <pre>
       * Encoded transaction
       * </pre>
       *
       * <code>string raw = 3;</code>
       * @param value The bytes for raw to set.
       * @return This builder for chaining.
       */
      public Builder setRawBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setRawBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Nebulas.Proto.SigningOutput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Nebulas.SigningOutput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "algorithm_",
              "signature_",
              "raw_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u000b\u0002\n" +
                "\u0003\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Nebulas.SigningOutput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Nebulas.SigningOutput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Nebulas.SigningOutput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Nebulas.Proto.SigningOutput)
    private static final wallet.core.jni.proto.Nebulas.SigningOutput DEFAULT_INSTANCE;
    static {
      SigningOutput defaultInstance = new SigningOutput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SigningOutput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Nebulas.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningOutput> PARSER;

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Nebulas.Proto.Data)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * <pre>
   * Generic data
   * </pre>
   *
   * Protobuf type {@code TW.Nebulas.Proto.Data}
   */
  public  static final class Data extends
      com.google.protobuf.GeneratedMessageLite<
          Data, Data.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Nebulas.Proto.Data)
      DataOrBuilder {
    private Data() {
      type_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.String type_;
    /**
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      return type_;
    }
    /**
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(type_);
    }
    /**
     * <code>string type = 1;</code>
     * @param value The type to set.
     */
    private void setType(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      type_ = value;
    }
    /**
     * <code>string type = 1;</code>
     */
    private void clearType() {
      
      type_ = getDefaultInstance().getType();
    }
    /**
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     */
    private void setTypeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      type_ = value.toStringUtf8();
      
    }

    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 2;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes payload = 2;</code>
     * @param value The payload to set.
     */
    private void setPayload(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      payload_ = value;
    }
    /**
     * <code>bytes payload = 2;</code>
     */
    private void clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
    }

    public static wallet.core.jni.proto.Nebulas.Data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Nebulas.Data prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Generic data
     * </pre>
     *
     * Protobuf type {@code TW.Nebulas.Proto.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Nebulas.Data, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Nebulas.Proto.Data)
        wallet.core.jni.proto.Nebulas.DataOrBuilder {
      // Construct using wallet.core.jni.proto.Nebulas.Data.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public java.lang.String getType() {
        return instance.getType();
      }
      /**
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTypeBytes() {
        return instance.getTypeBytes();
      }
      /**
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTypeBytes(value);
        return this;
      }

      /**
       * <code>bytes payload = 2;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return instance.getPayload();
      }
      /**
       * <code>bytes payload = 2;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPayload(value);
        return this;
      }
      /**
       * <code>bytes payload = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        copyOnWrite();
        instance.clearPayload();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Nebulas.Proto.Data)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Nebulas.Data();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "type_",
              "payload_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\n" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Nebulas.Data> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Nebulas.Data.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Nebulas.Data>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Nebulas.Proto.Data)
    private static final wallet.core.jni.proto.Nebulas.Data DEFAULT_INSTANCE;
    static {
      Data defaultInstance = new Data();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Data.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Nebulas.Data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Data> PARSER;

    public static com.google.protobuf.Parser<Data> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RawTransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Nebulas.Proto.RawTransaction)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * tx hash
     * </pre>
     *
     * <code>bytes hash = 1;</code>
     * @return The hash.
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <pre>
     * source address
     * </pre>
     *
     * <code>bytes from = 2;</code>
     * @return The from.
     */
    com.google.protobuf.ByteString getFrom();

    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>bytes to = 3;</code>
     * @return The to.
     */
    com.google.protobuf.ByteString getTo();

    /**
     * <pre>
     * amount (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes value = 4;</code>
     * @return The value.
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <pre>
     * Nonce (should be larger than in the last transaction of the account)
     * </pre>
     *
     * <code>uint64 nonce = 5;</code>
     * @return The nonce.
     */
    long getNonce();

    /**
     * <pre>
     * transaction timestamp
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * generic data
     * </pre>
     *
     * <code>.TW.Nebulas.Proto.Data data = 7;</code>
     * @return Whether the data field is set.
     */
    boolean hasData();
    /**
     * <pre>
     * generic data
     * </pre>
     *
     * <code>.TW.Nebulas.Proto.Data data = 7;</code>
     * @return The data.
     */
    wallet.core.jni.proto.Nebulas.Data getData();

    /**
     * <pre>
     * chain ID (4 bytes)
     * </pre>
     *
     * <code>uint32 chain_id = 8;</code>
     * @return The chainId.
     */
    int getChainId();

    /**
     * <pre>
     * gas price (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_price = 9;</code>
     * @return The gasPrice.
     */
    com.google.protobuf.ByteString getGasPrice();

    /**
     * <pre>
     * gas limit (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_limit = 10;</code>
     * @return The gasLimit.
     */
    com.google.protobuf.ByteString getGasLimit();

    /**
     * <pre>
     * algorithm
     * </pre>
     *
     * <code>uint32 alg = 11;</code>
     * @return The alg.
     */
    int getAlg();

    /**
     * <pre>
     * signature
     * </pre>
     *
     * <code>bytes sign = 12;</code>
     * @return The sign.
     */
    com.google.protobuf.ByteString getSign();
  }
  /**
   * <pre>
   * Raw transaction data
   * </pre>
   *
   * Protobuf type {@code TW.Nebulas.Proto.RawTransaction}
   */
  public  static final class RawTransaction extends
      com.google.protobuf.GeneratedMessageLite<
          RawTransaction, RawTransaction.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Nebulas.Proto.RawTransaction)
      RawTransactionOrBuilder {
    private RawTransaction() {
      hash_ = com.google.protobuf.ByteString.EMPTY;
      from_ = com.google.protobuf.ByteString.EMPTY;
      to_ = com.google.protobuf.ByteString.EMPTY;
      value_ = com.google.protobuf.ByteString.EMPTY;
      gasPrice_ = com.google.protobuf.ByteString.EMPTY;
      gasLimit_ = com.google.protobuf.ByteString.EMPTY;
      sign_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString hash_;
    /**
     * <pre>
     * tx hash
     * </pre>
     *
     * <code>bytes hash = 1;</code>
     * @return The hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }
    /**
     * <pre>
     * tx hash
     * </pre>
     *
     * <code>bytes hash = 1;</code>
     * @param value The hash to set.
     */
    private void setHash(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      hash_ = value;
    }
    /**
     * <pre>
     * tx hash
     * </pre>
     *
     * <code>bytes hash = 1;</code>
     */
    private void clearHash() {
      
      hash_ = getDefaultInstance().getHash();
    }

    public static final int FROM_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString from_;
    /**
     * <pre>
     * source address
     * </pre>
     *
     * <code>bytes from = 2;</code>
     * @return The from.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFrom() {
      return from_;
    }
    /**
     * <pre>
     * source address
     * </pre>
     *
     * <code>bytes from = 2;</code>
     * @param value The from to set.
     */
    private void setFrom(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      from_ = value;
    }
    /**
     * <pre>
     * source address
     * </pre>
     *
     * <code>bytes from = 2;</code>
     */
    private void clearFrom() {
      
      from_ = getDefaultInstance().getFrom();
    }

    public static final int TO_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString to_;
    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>bytes to = 3;</code>
     * @return The to.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTo() {
      return to_;
    }
    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>bytes to = 3;</code>
     * @param value The to to set.
     */
    private void setTo(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      to_ = value;
    }
    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>bytes to = 3;</code>
     */
    private void clearTo() {
      
      to_ = getDefaultInstance().getTo();
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString value_;
    /**
     * <pre>
     * amount (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes value = 4;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }
    /**
     * <pre>
     * amount (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes value = 4;</code>
     * @param value The value to set.
     */
    private void setValue(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      value_ = value;
    }
    /**
     * <pre>
     * amount (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes value = 4;</code>
     */
    private void clearValue() {
      
      value_ = getDefaultInstance().getValue();
    }

    public static final int NONCE_FIELD_NUMBER = 5;
    private long nonce_;
    /**
     * <pre>
     * Nonce (should be larger than in the last transaction of the account)
     * </pre>
     *
     * <code>uint64 nonce = 5;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public long getNonce() {
      return nonce_;
    }
    /**
     * <pre>
     * Nonce (should be larger than in the last transaction of the account)
     * </pre>
     *
     * <code>uint64 nonce = 5;</code>
     * @param value The nonce to set.
     */
    private void setNonce(long value) {
      
      nonce_ = value;
    }
    /**
     * <pre>
     * Nonce (should be larger than in the last transaction of the account)
     * </pre>
     *
     * <code>uint64 nonce = 5;</code>
     */
    private void clearNonce() {
      
      nonce_ = 0L;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timestamp_;
    /**
     * <pre>
     * transaction timestamp
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * transaction timestamp
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <pre>
     * transaction timestamp
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     */
    private void clearTimestamp() {
      
      timestamp_ = 0L;
    }

    public static final int DATA_FIELD_NUMBER = 7;
    private wallet.core.jni.proto.Nebulas.Data data_;
    /**
     * <pre>
     * generic data
     * </pre>
     *
     * <code>.TW.Nebulas.Proto.Data data = 7;</code>
     */
    @java.lang.Override
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <pre>
     * generic data
     * </pre>
     *
     * <code>.TW.Nebulas.Proto.Data data = 7;</code>
     */
    @java.lang.Override
    public wallet.core.jni.proto.Nebulas.Data getData() {
      return data_ == null ? wallet.core.jni.proto.Nebulas.Data.getDefaultInstance() : data_;
    }
    /**
     * <pre>
     * generic data
     * </pre>
     *
     * <code>.TW.Nebulas.Proto.Data data = 7;</code>
     */
    private void setData(wallet.core.jni.proto.Nebulas.Data value) {
      value.getClass();
  data_ = value;
      
      }
    /**
     * <pre>
     * generic data
     * </pre>
     *
     * <code>.TW.Nebulas.Proto.Data data = 7;</code>
     */
    @java.lang.SuppressWarnings({"ReferenceEquality"})
    private void mergeData(wallet.core.jni.proto.Nebulas.Data value) {
      value.getClass();
  if (data_ != null &&
          data_ != wallet.core.jni.proto.Nebulas.Data.getDefaultInstance()) {
        data_ =
          wallet.core.jni.proto.Nebulas.Data.newBuilder(data_).mergeFrom(value).buildPartial();
      } else {
        data_ = value;
      }
      
    }
    /**
     * <pre>
     * generic data
     * </pre>
     *
     * <code>.TW.Nebulas.Proto.Data data = 7;</code>
     */
    private void clearData() {  data_ = null;
      
    }

    public static final int CHAIN_ID_FIELD_NUMBER = 8;
    private int chainId_;
    /**
     * <pre>
     * chain ID (4 bytes)
     * </pre>
     *
     * <code>uint32 chain_id = 8;</code>
     * @return The chainId.
     */
    @java.lang.Override
    public int getChainId() {
      return chainId_;
    }
    /**
     * <pre>
     * chain ID (4 bytes)
     * </pre>
     *
     * <code>uint32 chain_id = 8;</code>
     * @param value The chainId to set.
     */
    private void setChainId(int value) {
      
      chainId_ = value;
    }
    /**
     * <pre>
     * chain ID (4 bytes)
     * </pre>
     *
     * <code>uint32 chain_id = 8;</code>
     */
    private void clearChainId() {
      
      chainId_ = 0;
    }

    public static final int GAS_PRICE_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString gasPrice_;
    /**
     * <pre>
     * gas price (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_price = 9;</code>
     * @return The gasPrice.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGasPrice() {
      return gasPrice_;
    }
    /**
     * <pre>
     * gas price (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_price = 9;</code>
     * @param value The gasPrice to set.
     */
    private void setGasPrice(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      gasPrice_ = value;
    }
    /**
     * <pre>
     * gas price (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_price = 9;</code>
     */
    private void clearGasPrice() {
      
      gasPrice_ = getDefaultInstance().getGasPrice();
    }

    public static final int GAS_LIMIT_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString gasLimit_;
    /**
     * <pre>
     * gas limit (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_limit = 10;</code>
     * @return The gasLimit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getGasLimit() {
      return gasLimit_;
    }
    /**
     * <pre>
     * gas limit (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_limit = 10;</code>
     * @param value The gasLimit to set.
     */
    private void setGasLimit(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      gasLimit_ = value;
    }
    /**
     * <pre>
     * gas limit (uint256, serialized little endian)
     * </pre>
     *
     * <code>bytes gas_limit = 10;</code>
     */
    private void clearGasLimit() {
      
      gasLimit_ = getDefaultInstance().getGasLimit();
    }

    public static final int ALG_FIELD_NUMBER = 11;
    private int alg_;
    /**
     * <pre>
     * algorithm
     * </pre>
     *
     * <code>uint32 alg = 11;</code>
     * @return The alg.
     */
    @java.lang.Override
    public int getAlg() {
      return alg_;
    }
    /**
     * <pre>
     * algorithm
     * </pre>
     *
     * <code>uint32 alg = 11;</code>
     * @param value The alg to set.
     */
    private void setAlg(int value) {
      
      alg_ = value;
    }
    /**
     * <pre>
     * algorithm
     * </pre>
     *
     * <code>uint32 alg = 11;</code>
     */
    private void clearAlg() {
      
      alg_ = 0;
    }

    public static final int SIGN_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString sign_;
    /**
     * <pre>
     * signature
     * </pre>
     *
     * <code>bytes sign = 12;</code>
     * @return The sign.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSign() {
      return sign_;
    }
    /**
     * <pre>
     * signature
     * </pre>
     *
     * <code>bytes sign = 12;</code>
     * @param value The sign to set.
     */
    private void setSign(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      sign_ = value;
    }
    /**
     * <pre>
     * signature
     * </pre>
     *
     * <code>bytes sign = 12;</code>
     */
    private void clearSign() {
      
      sign_ = getDefaultInstance().getSign();
    }

    public static wallet.core.jni.proto.Nebulas.RawTransaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Nebulas.RawTransaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Nebulas.RawTransaction prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Raw transaction data
     * </pre>
     *
     * Protobuf type {@code TW.Nebulas.Proto.RawTransaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Nebulas.RawTransaction, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Nebulas.Proto.RawTransaction)
        wallet.core.jni.proto.Nebulas.RawTransactionOrBuilder {
      // Construct using wallet.core.jni.proto.Nebulas.RawTransaction.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * tx hash
       * </pre>
       *
       * <code>bytes hash = 1;</code>
       * @return The hash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getHash() {
        return instance.getHash();
      }
      /**
       * <pre>
       * tx hash
       * </pre>
       *
       * <code>bytes hash = 1;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHash(value);
        return this;
      }
      /**
       * <pre>
       * tx hash
       * </pre>
       *
       * <code>bytes hash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        copyOnWrite();
        instance.clearHash();
        return this;
      }

      /**
       * <pre>
       * source address
       * </pre>
       *
       * <code>bytes from = 2;</code>
       * @return The from.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getFrom() {
        return instance.getFrom();
      }
      /**
       * <pre>
       * source address
       * </pre>
       *
       * <code>bytes from = 2;</code>
       * @param value The from to set.
       * @return This builder for chaining.
       */
      public Builder setFrom(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFrom(value);
        return this;
      }
      /**
       * <pre>
       * source address
       * </pre>
       *
       * <code>bytes from = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrom() {
        copyOnWrite();
        instance.clearFrom();
        return this;
      }

      /**
       * <pre>
       * destination address
       * </pre>
       *
       * <code>bytes to = 3;</code>
       * @return The to.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getTo() {
        return instance.getTo();
      }
      /**
       * <pre>
       * destination address
       * </pre>
       *
       * <code>bytes to = 3;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTo(value);
        return this;
      }
      /**
       * <pre>
       * destination address
       * </pre>
       *
       * <code>bytes to = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        copyOnWrite();
        instance.clearTo();
        return this;
      }

      /**
       * <pre>
       * amount (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes value = 4;</code>
       * @return The value.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getValue() {
        return instance.getValue();
      }
      /**
       * <pre>
       * amount (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes value = 4;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setValue(value);
        return this;
      }
      /**
       * <pre>
       * amount (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        copyOnWrite();
        instance.clearValue();
        return this;
      }

      /**
       * <pre>
       * Nonce (should be larger than in the last transaction of the account)
       * </pre>
       *
       * <code>uint64 nonce = 5;</code>
       * @return The nonce.
       */
      @java.lang.Override
      public long getNonce() {
        return instance.getNonce();
      }
      /**
       * <pre>
       * Nonce (should be larger than in the last transaction of the account)
       * </pre>
       *
       * <code>uint64 nonce = 5;</code>
       * @param value The nonce to set.
       * @return This builder for chaining.
       */
      public Builder setNonce(long value) {
        copyOnWrite();
        instance.setNonce(value);
        return this;
      }
      /**
       * <pre>
       * Nonce (should be larger than in the last transaction of the account)
       * </pre>
       *
       * <code>uint64 nonce = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearNonce() {
        copyOnWrite();
        instance.clearNonce();
        return this;
      }

      /**
       * <pre>
       * transaction timestamp
       * </pre>
       *
       * <code>int64 timestamp = 6;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * transaction timestamp
       * </pre>
       *
       * <code>int64 timestamp = 6;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * transaction timestamp
       * </pre>
       *
       * <code>int64 timestamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <pre>
       * generic data
       * </pre>
       *
       * <code>.TW.Nebulas.Proto.Data data = 7;</code>
       */
      @java.lang.Override
      public boolean hasData() {
        return instance.hasData();
      }
      /**
       * <pre>
       * generic data
       * </pre>
       *
       * <code>.TW.Nebulas.Proto.Data data = 7;</code>
       */
      @java.lang.Override
      public wallet.core.jni.proto.Nebulas.Data getData() {
        return instance.getData();
      }
      /**
       * <pre>
       * generic data
       * </pre>
       *
       * <code>.TW.Nebulas.Proto.Data data = 7;</code>
       */
      public Builder setData(wallet.core.jni.proto.Nebulas.Data value) {
        copyOnWrite();
        instance.setData(value);
        return this;
        }
      /**
       * <pre>
       * generic data
       * </pre>
       *
       * <code>.TW.Nebulas.Proto.Data data = 7;</code>
       */
      public Builder setData(
          wallet.core.jni.proto.Nebulas.Data.Builder builderForValue) {
        copyOnWrite();
        instance.setData(builderForValue.build());
        return this;
      }
      /**
       * <pre>
       * generic data
       * </pre>
       *
       * <code>.TW.Nebulas.Proto.Data data = 7;</code>
       */
      public Builder mergeData(wallet.core.jni.proto.Nebulas.Data value) {
        copyOnWrite();
        instance.mergeData(value);
        return this;
      }
      /**
       * <pre>
       * generic data
       * </pre>
       *
       * <code>.TW.Nebulas.Proto.Data data = 7;</code>
       */
      public Builder clearData() {  copyOnWrite();
        instance.clearData();
        return this;
      }

      /**
       * <pre>
       * chain ID (4 bytes)
       * </pre>
       *
       * <code>uint32 chain_id = 8;</code>
       * @return The chainId.
       */
      @java.lang.Override
      public int getChainId() {
        return instance.getChainId();
      }
      /**
       * <pre>
       * chain ID (4 bytes)
       * </pre>
       *
       * <code>uint32 chain_id = 8;</code>
       * @param value The chainId to set.
       * @return This builder for chaining.
       */
      public Builder setChainId(int value) {
        copyOnWrite();
        instance.setChainId(value);
        return this;
      }
      /**
       * <pre>
       * chain ID (4 bytes)
       * </pre>
       *
       * <code>uint32 chain_id = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearChainId() {
        copyOnWrite();
        instance.clearChainId();
        return this;
      }

      /**
       * <pre>
       * gas price (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_price = 9;</code>
       * @return The gasPrice.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGasPrice() {
        return instance.getGasPrice();
      }
      /**
       * <pre>
       * gas price (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_price = 9;</code>
       * @param value The gasPrice to set.
       * @return This builder for chaining.
       */
      public Builder setGasPrice(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGasPrice(value);
        return this;
      }
      /**
       * <pre>
       * gas price (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_price = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasPrice() {
        copyOnWrite();
        instance.clearGasPrice();
        return this;
      }

      /**
       * <pre>
       * gas limit (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_limit = 10;</code>
       * @return The gasLimit.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getGasLimit() {
        return instance.getGasLimit();
      }
      /**
       * <pre>
       * gas limit (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_limit = 10;</code>
       * @param value The gasLimit to set.
       * @return This builder for chaining.
       */
      public Builder setGasLimit(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGasLimit(value);
        return this;
      }
      /**
       * <pre>
       * gas limit (uint256, serialized little endian)
       * </pre>
       *
       * <code>bytes gas_limit = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearGasLimit() {
        copyOnWrite();
        instance.clearGasLimit();
        return this;
      }

      /**
       * <pre>
       * algorithm
       * </pre>
       *
       * <code>uint32 alg = 11;</code>
       * @return The alg.
       */
      @java.lang.Override
      public int getAlg() {
        return instance.getAlg();
      }
      /**
       * <pre>
       * algorithm
       * </pre>
       *
       * <code>uint32 alg = 11;</code>
       * @param value The alg to set.
       * @return This builder for chaining.
       */
      public Builder setAlg(int value) {
        copyOnWrite();
        instance.setAlg(value);
        return this;
      }
      /**
       * <pre>
       * algorithm
       * </pre>
       *
       * <code>uint32 alg = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlg() {
        copyOnWrite();
        instance.clearAlg();
        return this;
      }

      /**
       * <pre>
       * signature
       * </pre>
       *
       * <code>bytes sign = 12;</code>
       * @return The sign.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSign() {
        return instance.getSign();
      }
      /**
       * <pre>
       * signature
       * </pre>
       *
       * <code>bytes sign = 12;</code>
       * @param value The sign to set.
       * @return This builder for chaining.
       */
      public Builder setSign(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSign(value);
        return this;
      }
      /**
       * <pre>
       * signature
       * </pre>
       *
       * <code>bytes sign = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearSign() {
        copyOnWrite();
        instance.clearSign();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Nebulas.Proto.RawTransaction)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Nebulas.RawTransaction();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "hash_",
              "from_",
              "to_",
              "value_",
              "nonce_",
              "timestamp_",
              "data_",
              "chainId_",
              "gasPrice_",
              "gasLimit_",
              "alg_",
              "sign_",
            };
            java.lang.String info =
                "\u0000\f\u0000\u0000\u0001\f\f\u0000\u0000\u0000\u0001\n\u0002\n\u0003\n\u0004\n" +
                "\u0005\u0003\u0006\u0002\u0007\t\b\u000b\t\n\n\n\u000b\u000b\f\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Nebulas.RawTransaction> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Nebulas.RawTransaction.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Nebulas.RawTransaction>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Nebulas.Proto.RawTransaction)
    private static final wallet.core.jni.proto.Nebulas.RawTransaction DEFAULT_INSTANCE;
    static {
      RawTransaction defaultInstance = new RawTransaction();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RawTransaction.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Nebulas.RawTransaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RawTransaction> PARSER;

    public static com.google.protobuf.Parser<RawTransaction> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
