// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransactionCompiler.proto

package wallet.core.jni.proto;

public final class TransactionCompiler {
  private TransactionCompiler() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PreSigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.TxCompiler.Proto.PreSigningOutput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *&#47; Pre-image data hash that will be used for signing
     * </pre>
     *
     * <code>bytes data_hash = 1;</code>
     * @return The dataHash.
     */
    com.google.protobuf.ByteString getDataHash();

    /**
     * <pre>
     *&#47; Pre-image data
     * </pre>
     *
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <pre>
     *&#47; error code, 0 is ok, other codes will be treated as errors
     * </pre>
     *
     * <code>.TW.Common.Proto.SigningError error = 3;</code>
     * @return The enum numeric value on the wire for error.
     */
    int getErrorValue();
    /**
     * <pre>
     *&#47; error code, 0 is ok, other codes will be treated as errors
     * </pre>
     *
     * <code>.TW.Common.Proto.SigningError error = 3;</code>
     * @return The error.
     */
    wallet.core.jni.proto.Common.SigningError getError();

    /**
     * <pre>
     *&#47; error code description
     * </pre>
     *
     * <code>string error_message = 4;</code>
     * @return The errorMessage.
     */
    java.lang.String getErrorMessage();
    /**
     * <pre>
     *&#47; error code description
     * </pre>
     *
     * <code>string error_message = 4;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * <pre>
   *&#47; Transaction pre-signing output
   * </pre>
   *
   * Protobuf type {@code TW.TxCompiler.Proto.PreSigningOutput}
   */
  public  static final class PreSigningOutput extends
      com.google.protobuf.GeneratedMessageLite<
          PreSigningOutput, PreSigningOutput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.TxCompiler.Proto.PreSigningOutput)
      PreSigningOutputOrBuilder {
    private PreSigningOutput() {
      dataHash_ = com.google.protobuf.ByteString.EMPTY;
      data_ = com.google.protobuf.ByteString.EMPTY;
      errorMessage_ = "";
    }
    public static final int DATA_HASH_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString dataHash_;
    /**
     * <pre>
     *&#47; Pre-image data hash that will be used for signing
     * </pre>
     *
     * <code>bytes data_hash = 1;</code>
     * @return The dataHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDataHash() {
      return dataHash_;
    }
    /**
     * <pre>
     *&#47; Pre-image data hash that will be used for signing
     * </pre>
     *
     * <code>bytes data_hash = 1;</code>
     * @param value The dataHash to set.
     */
    private void setDataHash(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      dataHash_ = value;
    }
    /**
     * <pre>
     *&#47; Pre-image data hash that will be used for signing
     * </pre>
     *
     * <code>bytes data_hash = 1;</code>
     */
    private void clearDataHash() {
      
      dataHash_ = getDefaultInstance().getDataHash();
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *&#47; Pre-image data
     * </pre>
     *
     * <code>bytes data = 2;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <pre>
     *&#47; Pre-image data
     * </pre>
     *
     * <code>bytes data = 2;</code>
     * @param value The data to set.
     */
    private void setData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      data_ = value;
    }
    /**
     * <pre>
     *&#47; Pre-image data
     * </pre>
     *
     * <code>bytes data = 2;</code>
     */
    private void clearData() {
      
      data_ = getDefaultInstance().getData();
    }

    public static final int ERROR_FIELD_NUMBER = 3;
    private int error_;
    /**
     * <pre>
     *&#47; error code, 0 is ok, other codes will be treated as errors
     * </pre>
     *
     * <code>.TW.Common.Proto.SigningError error = 3;</code>
     * @return The enum numeric value on the wire for error.
     */
    @java.lang.Override
    public int getErrorValue() {
      return error_;
    }
    /**
     * <pre>
     *&#47; error code, 0 is ok, other codes will be treated as errors
     * </pre>
     *
     * <code>.TW.Common.Proto.SigningError error = 3;</code>
     * @return The error.
     */
    @java.lang.Override
    public wallet.core.jni.proto.Common.SigningError getError() {
      wallet.core.jni.proto.Common.SigningError result = wallet.core.jni.proto.Common.SigningError.forNumber(error_);
      return result == null ? wallet.core.jni.proto.Common.SigningError.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *&#47; error code, 0 is ok, other codes will be treated as errors
     * </pre>
     *
     * <code>.TW.Common.Proto.SigningError error = 3;</code>
     * @param value The enum numeric value on the wire for error to set.
     */
    private void setErrorValue(int value) {
        error_ = value;
    }
    /**
     * <pre>
     *&#47; error code, 0 is ok, other codes will be treated as errors
     * </pre>
     *
     * <code>.TW.Common.Proto.SigningError error = 3;</code>
     * @param value The error to set.
     */
    private void setError(wallet.core.jni.proto.Common.SigningError value) {
      error_ = value.getNumber();
      
    }
    /**
     * <pre>
     *&#47; error code, 0 is ok, other codes will be treated as errors
     * </pre>
     *
     * <code>.TW.Common.Proto.SigningError error = 3;</code>
     */
    private void clearError() {
      
      error_ = 0;
    }

    public static final int ERROR_MESSAGE_FIELD_NUMBER = 4;
    private java.lang.String errorMessage_;
    /**
     * <pre>
     *&#47; error code description
     * </pre>
     *
     * <code>string error_message = 4;</code>
     * @return The errorMessage.
     */
    @java.lang.Override
    public java.lang.String getErrorMessage() {
      return errorMessage_;
    }
    /**
     * <pre>
     *&#47; error code description
     * </pre>
     *
     * <code>string error_message = 4;</code>
     * @return The bytes for errorMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errorMessage_);
    }
    /**
     * <pre>
     *&#47; error code description
     * </pre>
     *
     * <code>string error_message = 4;</code>
     * @param value The errorMessage to set.
     */
    private void setErrorMessage(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      errorMessage_ = value;
    }
    /**
     * <pre>
     *&#47; error code description
     * </pre>
     *
     * <code>string error_message = 4;</code>
     */
    private void clearErrorMessage() {
      
      errorMessage_ = getDefaultInstance().getErrorMessage();
    }
    /**
     * <pre>
     *&#47; error code description
     * </pre>
     *
     * <code>string error_message = 4;</code>
     * @param value The bytes for errorMessage to set.
     */
    private void setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      errorMessage_ = value.toStringUtf8();
      
    }

    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.TransactionCompiler.PreSigningOutput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     *&#47; Transaction pre-signing output
     * </pre>
     *
     * Protobuf type {@code TW.TxCompiler.Proto.PreSigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.TransactionCompiler.PreSigningOutput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.TxCompiler.Proto.PreSigningOutput)
        wallet.core.jni.proto.TransactionCompiler.PreSigningOutputOrBuilder {
      // Construct using wallet.core.jni.proto.TransactionCompiler.PreSigningOutput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *&#47; Pre-image data hash that will be used for signing
       * </pre>
       *
       * <code>bytes data_hash = 1;</code>
       * @return The dataHash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getDataHash() {
        return instance.getDataHash();
      }
      /**
       * <pre>
       *&#47; Pre-image data hash that will be used for signing
       * </pre>
       *
       * <code>bytes data_hash = 1;</code>
       * @param value The dataHash to set.
       * @return This builder for chaining.
       */
      public Builder setDataHash(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDataHash(value);
        return this;
      }
      /**
       * <pre>
       *&#47; Pre-image data hash that will be used for signing
       * </pre>
       *
       * <code>bytes data_hash = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataHash() {
        copyOnWrite();
        instance.clearDataHash();
        return this;
      }

      /**
       * <pre>
       *&#47; Pre-image data
       * </pre>
       *
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return instance.getData();
      }
      /**
       * <pre>
       *&#47; Pre-image data
       * </pre>
       *
       * <code>bytes data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setData(value);
        return this;
      }
      /**
       * <pre>
       *&#47; Pre-image data
       * </pre>
       *
       * <code>bytes data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }

      /**
       * <pre>
       *&#47; error code, 0 is ok, other codes will be treated as errors
       * </pre>
       *
       * <code>.TW.Common.Proto.SigningError error = 3;</code>
       * @return The enum numeric value on the wire for error.
       */
      @java.lang.Override
      public int getErrorValue() {
        return instance.getErrorValue();
      }
      /**
       * <pre>
       *&#47; error code, 0 is ok, other codes will be treated as errors
       * </pre>
       *
       * <code>.TW.Common.Proto.SigningError error = 3;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setErrorValue(int value) {
        copyOnWrite();
        instance.setErrorValue(value);
        return this;
      }
      /**
       * <pre>
       *&#47; error code, 0 is ok, other codes will be treated as errors
       * </pre>
       *
       * <code>.TW.Common.Proto.SigningError error = 3;</code>
       * @return The error.
       */
      @java.lang.Override
      public wallet.core.jni.proto.Common.SigningError getError() {
        return instance.getError();
      }
      /**
       * <pre>
       *&#47; error code, 0 is ok, other codes will be treated as errors
       * </pre>
       *
       * <code>.TW.Common.Proto.SigningError error = 3;</code>
       * @param value The enum numeric value on the wire for error to set.
       * @return This builder for chaining.
       */
      public Builder setError(wallet.core.jni.proto.Common.SigningError value) {
        copyOnWrite();
        instance.setError(value);
        return this;
      }
      /**
       * <pre>
       *&#47; error code, 0 is ok, other codes will be treated as errors
       * </pre>
       *
       * <code>.TW.Common.Proto.SigningError error = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        copyOnWrite();
        instance.clearError();
        return this;
      }

      /**
       * <pre>
       *&#47; error code description
       * </pre>
       *
       * <code>string error_message = 4;</code>
       * @return The errorMessage.
       */
      @java.lang.Override
      public java.lang.String getErrorMessage() {
        return instance.getErrorMessage();
      }
      /**
       * <pre>
       *&#47; error code description
       * </pre>
       *
       * <code>string error_message = 4;</code>
       * @return The bytes for errorMessage.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        return instance.getErrorMessageBytes();
      }
      /**
       * <pre>
       *&#47; error code description
       * </pre>
       *
       * <code>string error_message = 4;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setErrorMessage(value);
        return this;
      }
      /**
       * <pre>
       *&#47; error code description
       * </pre>
       *
       * <code>string error_message = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        copyOnWrite();
        instance.clearErrorMessage();
        return this;
      }
      /**
       * <pre>
       *&#47; error code description
       * </pre>
       *
       * <code>string error_message = 4;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrorMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.TxCompiler.Proto.PreSigningOutput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.TransactionCompiler.PreSigningOutput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "dataHash_",
              "data_",
              "error_",
              "errorMessage_",
            };
            java.lang.String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\n\u0002\n\u0003" +
                "\f\u0004\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.TransactionCompiler.PreSigningOutput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.TransactionCompiler.PreSigningOutput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.TransactionCompiler.PreSigningOutput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.TxCompiler.Proto.PreSigningOutput)
    private static final wallet.core.jni.proto.TransactionCompiler.PreSigningOutput DEFAULT_INSTANCE;
    static {
      PreSigningOutput defaultInstance = new PreSigningOutput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PreSigningOutput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.TransactionCompiler.PreSigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PreSigningOutput> PARSER;

    public static com.google.protobuf.Parser<PreSigningOutput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
