// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Waves.proto

package wallet.core.jni.proto;

public final class Waves {
  private Waves() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TransferMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Waves.Proto.TransferMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * amount
     * </pre>
     *
     * <code>int64 amount = 1;</code>
     * @return The amount.
     */
    long getAmount();

    /**
     * <pre>
     * asset ID
     * </pre>
     *
     * <code>string asset = 2;</code>
     * @return The asset.
     */
    java.lang.String getAsset();
    /**
     * <pre>
     * asset ID
     * </pre>
     *
     * <code>string asset = 2;</code>
     * @return The bytes for asset.
     */
    com.google.protobuf.ByteString
        getAssetBytes();

    /**
     * <pre>
     * minimum 0.001 Waves (100000 Wavelets) for now
     * </pre>
     *
     * <code>int64 fee = 3;</code>
     * @return The fee.
     */
    long getFee();

    /**
     * <pre>
     * asset of the fee
     * </pre>
     *
     * <code>string fee_asset = 4;</code>
     * @return The feeAsset.
     */
    java.lang.String getFeeAsset();
    /**
     * <pre>
     * asset of the fee
     * </pre>
     *
     * <code>string fee_asset = 4;</code>
     * @return The bytes for feeAsset.
     */
    com.google.protobuf.ByteString
        getFeeAssetBytes();

    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>string to = 5;</code>
     * @return The to.
     */
    java.lang.String getTo();
    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>string to = 5;</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     * any 140 bytes payload, will be displayed to the client as utf-8 string
     * </pre>
     *
     * <code>bytes attachment = 6;</code>
     * @return The attachment.
     */
    com.google.protobuf.ByteString getAttachment();
  }
  /**
   * <pre>
   * Transfer transaction
   * </pre>
   *
   * Protobuf type {@code TW.Waves.Proto.TransferMessage}
   */
  public  static final class TransferMessage extends
      com.google.protobuf.GeneratedMessageLite<
          TransferMessage, TransferMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Waves.Proto.TransferMessage)
      TransferMessageOrBuilder {
    private TransferMessage() {
      asset_ = "";
      feeAsset_ = "";
      to_ = "";
      attachment_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int AMOUNT_FIELD_NUMBER = 1;
    private long amount_;
    /**
     * <pre>
     * amount
     * </pre>
     *
     * <code>int64 amount = 1;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * amount
     * </pre>
     *
     * <code>int64 amount = 1;</code>
     * @param value The amount to set.
     */
    private void setAmount(long value) {
      
      amount_ = value;
    }
    /**
     * <pre>
     * amount
     * </pre>
     *
     * <code>int64 amount = 1;</code>
     */
    private void clearAmount() {
      
      amount_ = 0L;
    }

    public static final int ASSET_FIELD_NUMBER = 2;
    private java.lang.String asset_;
    /**
     * <pre>
     * asset ID
     * </pre>
     *
     * <code>string asset = 2;</code>
     * @return The asset.
     */
    @java.lang.Override
    public java.lang.String getAsset() {
      return asset_;
    }
    /**
     * <pre>
     * asset ID
     * </pre>
     *
     * <code>string asset = 2;</code>
     * @return The bytes for asset.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAssetBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(asset_);
    }
    /**
     * <pre>
     * asset ID
     * </pre>
     *
     * <code>string asset = 2;</code>
     * @param value The asset to set.
     */
    private void setAsset(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      asset_ = value;
    }
    /**
     * <pre>
     * asset ID
     * </pre>
     *
     * <code>string asset = 2;</code>
     */
    private void clearAsset() {
      
      asset_ = getDefaultInstance().getAsset();
    }
    /**
     * <pre>
     * asset ID
     * </pre>
     *
     * <code>string asset = 2;</code>
     * @param value The bytes for asset to set.
     */
    private void setAssetBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      asset_ = value.toStringUtf8();
      
    }

    public static final int FEE_FIELD_NUMBER = 3;
    private long fee_;
    /**
     * <pre>
     * minimum 0.001 Waves (100000 Wavelets) for now
     * </pre>
     *
     * <code>int64 fee = 3;</code>
     * @return The fee.
     */
    @java.lang.Override
    public long getFee() {
      return fee_;
    }
    /**
     * <pre>
     * minimum 0.001 Waves (100000 Wavelets) for now
     * </pre>
     *
     * <code>int64 fee = 3;</code>
     * @param value The fee to set.
     */
    private void setFee(long value) {
      
      fee_ = value;
    }
    /**
     * <pre>
     * minimum 0.001 Waves (100000 Wavelets) for now
     * </pre>
     *
     * <code>int64 fee = 3;</code>
     */
    private void clearFee() {
      
      fee_ = 0L;
    }

    public static final int FEE_ASSET_FIELD_NUMBER = 4;
    private java.lang.String feeAsset_;
    /**
     * <pre>
     * asset of the fee
     * </pre>
     *
     * <code>string fee_asset = 4;</code>
     * @return The feeAsset.
     */
    @java.lang.Override
    public java.lang.String getFeeAsset() {
      return feeAsset_;
    }
    /**
     * <pre>
     * asset of the fee
     * </pre>
     *
     * <code>string fee_asset = 4;</code>
     * @return The bytes for feeAsset.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFeeAssetBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(feeAsset_);
    }
    /**
     * <pre>
     * asset of the fee
     * </pre>
     *
     * <code>string fee_asset = 4;</code>
     * @param value The feeAsset to set.
     */
    private void setFeeAsset(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      feeAsset_ = value;
    }
    /**
     * <pre>
     * asset of the fee
     * </pre>
     *
     * <code>string fee_asset = 4;</code>
     */
    private void clearFeeAsset() {
      
      feeAsset_ = getDefaultInstance().getFeeAsset();
    }
    /**
     * <pre>
     * asset of the fee
     * </pre>
     *
     * <code>string fee_asset = 4;</code>
     * @param value The bytes for feeAsset to set.
     */
    private void setFeeAssetBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      feeAsset_ = value.toStringUtf8();
      
    }

    public static final int TO_FIELD_NUMBER = 5;
    private java.lang.String to_;
    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>string to = 5;</code>
     * @return The to.
     */
    @java.lang.Override
    public java.lang.String getTo() {
      return to_;
    }
    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>string to = 5;</code>
     * @return The bytes for to.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(to_);
    }
    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>string to = 5;</code>
     * @param value The to to set.
     */
    private void setTo(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      to_ = value;
    }
    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>string to = 5;</code>
     */
    private void clearTo() {
      
      to_ = getDefaultInstance().getTo();
    }
    /**
     * <pre>
     * destination address
     * </pre>
     *
     * <code>string to = 5;</code>
     * @param value The bytes for to to set.
     */
    private void setToBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      to_ = value.toStringUtf8();
      
    }

    public static final int ATTACHMENT_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString attachment_;
    /**
     * <pre>
     * any 140 bytes payload, will be displayed to the client as utf-8 string
     * </pre>
     *
     * <code>bytes attachment = 6;</code>
     * @return The attachment.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAttachment() {
      return attachment_;
    }
    /**
     * <pre>
     * any 140 bytes payload, will be displayed to the client as utf-8 string
     * </pre>
     *
     * <code>bytes attachment = 6;</code>
     * @param value The attachment to set.
     */
    private void setAttachment(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      attachment_ = value;
    }
    /**
     * <pre>
     * any 140 bytes payload, will be displayed to the client as utf-8 string
     * </pre>
     *
     * <code>bytes attachment = 6;</code>
     */
    private void clearAttachment() {
      
      attachment_ = getDefaultInstance().getAttachment();
    }

    public static wallet.core.jni.proto.Waves.TransferMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.TransferMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Waves.TransferMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Transfer transaction
     * </pre>
     *
     * Protobuf type {@code TW.Waves.Proto.TransferMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Waves.TransferMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Waves.Proto.TransferMessage)
        wallet.core.jni.proto.Waves.TransferMessageOrBuilder {
      // Construct using wallet.core.jni.proto.Waves.TransferMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * amount
       * </pre>
       *
       * <code>int64 amount = 1;</code>
       * @return The amount.
       */
      @java.lang.Override
      public long getAmount() {
        return instance.getAmount();
      }
      /**
       * <pre>
       * amount
       * </pre>
       *
       * <code>int64 amount = 1;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(long value) {
        copyOnWrite();
        instance.setAmount(value);
        return this;
      }
      /**
       * <pre>
       * amount
       * </pre>
       *
       * <code>int64 amount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        copyOnWrite();
        instance.clearAmount();
        return this;
      }

      /**
       * <pre>
       * asset ID
       * </pre>
       *
       * <code>string asset = 2;</code>
       * @return The asset.
       */
      @java.lang.Override
      public java.lang.String getAsset() {
        return instance.getAsset();
      }
      /**
       * <pre>
       * asset ID
       * </pre>
       *
       * <code>string asset = 2;</code>
       * @return The bytes for asset.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAssetBytes() {
        return instance.getAssetBytes();
      }
      /**
       * <pre>
       * asset ID
       * </pre>
       *
       * <code>string asset = 2;</code>
       * @param value The asset to set.
       * @return This builder for chaining.
       */
      public Builder setAsset(
          java.lang.String value) {
        copyOnWrite();
        instance.setAsset(value);
        return this;
      }
      /**
       * <pre>
       * asset ID
       * </pre>
       *
       * <code>string asset = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAsset() {
        copyOnWrite();
        instance.clearAsset();
        return this;
      }
      /**
       * <pre>
       * asset ID
       * </pre>
       *
       * <code>string asset = 2;</code>
       * @param value The bytes for asset to set.
       * @return This builder for chaining.
       */
      public Builder setAssetBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAssetBytes(value);
        return this;
      }

      /**
       * <pre>
       * minimum 0.001 Waves (100000 Wavelets) for now
       * </pre>
       *
       * <code>int64 fee = 3;</code>
       * @return The fee.
       */
      @java.lang.Override
      public long getFee() {
        return instance.getFee();
      }
      /**
       * <pre>
       * minimum 0.001 Waves (100000 Wavelets) for now
       * </pre>
       *
       * <code>int64 fee = 3;</code>
       * @param value The fee to set.
       * @return This builder for chaining.
       */
      public Builder setFee(long value) {
        copyOnWrite();
        instance.setFee(value);
        return this;
      }
      /**
       * <pre>
       * minimum 0.001 Waves (100000 Wavelets) for now
       * </pre>
       *
       * <code>int64 fee = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFee() {
        copyOnWrite();
        instance.clearFee();
        return this;
      }

      /**
       * <pre>
       * asset of the fee
       * </pre>
       *
       * <code>string fee_asset = 4;</code>
       * @return The feeAsset.
       */
      @java.lang.Override
      public java.lang.String getFeeAsset() {
        return instance.getFeeAsset();
      }
      /**
       * <pre>
       * asset of the fee
       * </pre>
       *
       * <code>string fee_asset = 4;</code>
       * @return The bytes for feeAsset.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getFeeAssetBytes() {
        return instance.getFeeAssetBytes();
      }
      /**
       * <pre>
       * asset of the fee
       * </pre>
       *
       * <code>string fee_asset = 4;</code>
       * @param value The feeAsset to set.
       * @return This builder for chaining.
       */
      public Builder setFeeAsset(
          java.lang.String value) {
        copyOnWrite();
        instance.setFeeAsset(value);
        return this;
      }
      /**
       * <pre>
       * asset of the fee
       * </pre>
       *
       * <code>string fee_asset = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFeeAsset() {
        copyOnWrite();
        instance.clearFeeAsset();
        return this;
      }
      /**
       * <pre>
       * asset of the fee
       * </pre>
       *
       * <code>string fee_asset = 4;</code>
       * @param value The bytes for feeAsset to set.
       * @return This builder for chaining.
       */
      public Builder setFeeAssetBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFeeAssetBytes(value);
        return this;
      }

      /**
       * <pre>
       * destination address
       * </pre>
       *
       * <code>string to = 5;</code>
       * @return The to.
       */
      @java.lang.Override
      public java.lang.String getTo() {
        return instance.getTo();
      }
      /**
       * <pre>
       * destination address
       * </pre>
       *
       * <code>string to = 5;</code>
       * @return The bytes for to.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getToBytes() {
        return instance.getToBytes();
      }
      /**
       * <pre>
       * destination address
       * </pre>
       *
       * <code>string to = 5;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          java.lang.String value) {
        copyOnWrite();
        instance.setTo(value);
        return this;
      }
      /**
       * <pre>
       * destination address
       * </pre>
       *
       * <code>string to = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        copyOnWrite();
        instance.clearTo();
        return this;
      }
      /**
       * <pre>
       * destination address
       * </pre>
       *
       * <code>string to = 5;</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setToBytes(value);
        return this;
      }

      /**
       * <pre>
       * any 140 bytes payload, will be displayed to the client as utf-8 string
       * </pre>
       *
       * <code>bytes attachment = 6;</code>
       * @return The attachment.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAttachment() {
        return instance.getAttachment();
      }
      /**
       * <pre>
       * any 140 bytes payload, will be displayed to the client as utf-8 string
       * </pre>
       *
       * <code>bytes attachment = 6;</code>
       * @param value The attachment to set.
       * @return This builder for chaining.
       */
      public Builder setAttachment(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAttachment(value);
        return this;
      }
      /**
       * <pre>
       * any 140 bytes payload, will be displayed to the client as utf-8 string
       * </pre>
       *
       * <code>bytes attachment = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttachment() {
        copyOnWrite();
        instance.clearAttachment();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Waves.Proto.TransferMessage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Waves.TransferMessage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "amount_",
              "asset_",
              "fee_",
              "feeAsset_",
              "to_",
              "attachment_",
            };
            java.lang.String info =
                "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0002\u0002\u0208" +
                "\u0003\u0002\u0004\u0208\u0005\u0208\u0006\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Waves.TransferMessage> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Waves.TransferMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Waves.TransferMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Waves.Proto.TransferMessage)
    private static final wallet.core.jni.proto.Waves.TransferMessage DEFAULT_INSTANCE;
    static {
      TransferMessage defaultInstance = new TransferMessage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        TransferMessage.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Waves.TransferMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TransferMessage> PARSER;

    public static com.google.protobuf.Parser<TransferMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LeaseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Waves.Proto.LeaseMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * amount
     * </pre>
     *
     * <code>int64 amount = 1;</code>
     * @return The amount.
     */
    long getAmount();

    /**
     * <pre>
     * destination
     * </pre>
     *
     * <code>string to = 2;</code>
     * @return The to.
     */
    java.lang.String getTo();
    /**
     * <pre>
     * destination
     * </pre>
     *
     * <code>string to = 2;</code>
     * @return The bytes for to.
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <pre>
     * minimum 0.001 Waves (100000 Wavelets) for now
     * </pre>
     *
     * <code>int64 fee = 3;</code>
     * @return The fee.
     */
    long getFee();
  }
  /**
   * <pre>
   * Lease transaction
   * </pre>
   *
   * Protobuf type {@code TW.Waves.Proto.LeaseMessage}
   */
  public  static final class LeaseMessage extends
      com.google.protobuf.GeneratedMessageLite<
          LeaseMessage, LeaseMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Waves.Proto.LeaseMessage)
      LeaseMessageOrBuilder {
    private LeaseMessage() {
      to_ = "";
    }
    public static final int AMOUNT_FIELD_NUMBER = 1;
    private long amount_;
    /**
     * <pre>
     * amount
     * </pre>
     *
     * <code>int64 amount = 1;</code>
     * @return The amount.
     */
    @java.lang.Override
    public long getAmount() {
      return amount_;
    }
    /**
     * <pre>
     * amount
     * </pre>
     *
     * <code>int64 amount = 1;</code>
     * @param value The amount to set.
     */
    private void setAmount(long value) {
      
      amount_ = value;
    }
    /**
     * <pre>
     * amount
     * </pre>
     *
     * <code>int64 amount = 1;</code>
     */
    private void clearAmount() {
      
      amount_ = 0L;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private java.lang.String to_;
    /**
     * <pre>
     * destination
     * </pre>
     *
     * <code>string to = 2;</code>
     * @return The to.
     */
    @java.lang.Override
    public java.lang.String getTo() {
      return to_;
    }
    /**
     * <pre>
     * destination
     * </pre>
     *
     * <code>string to = 2;</code>
     * @return The bytes for to.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getToBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(to_);
    }
    /**
     * <pre>
     * destination
     * </pre>
     *
     * <code>string to = 2;</code>
     * @param value The to to set.
     */
    private void setTo(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      to_ = value;
    }
    /**
     * <pre>
     * destination
     * </pre>
     *
     * <code>string to = 2;</code>
     */
    private void clearTo() {
      
      to_ = getDefaultInstance().getTo();
    }
    /**
     * <pre>
     * destination
     * </pre>
     *
     * <code>string to = 2;</code>
     * @param value The bytes for to to set.
     */
    private void setToBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      to_ = value.toStringUtf8();
      
    }

    public static final int FEE_FIELD_NUMBER = 3;
    private long fee_;
    /**
     * <pre>
     * minimum 0.001 Waves (100000 Wavelets) for now
     * </pre>
     *
     * <code>int64 fee = 3;</code>
     * @return The fee.
     */
    @java.lang.Override
    public long getFee() {
      return fee_;
    }
    /**
     * <pre>
     * minimum 0.001 Waves (100000 Wavelets) for now
     * </pre>
     *
     * <code>int64 fee = 3;</code>
     * @param value The fee to set.
     */
    private void setFee(long value) {
      
      fee_ = value;
    }
    /**
     * <pre>
     * minimum 0.001 Waves (100000 Wavelets) for now
     * </pre>
     *
     * <code>int64 fee = 3;</code>
     */
    private void clearFee() {
      
      fee_ = 0L;
    }

    public static wallet.core.jni.proto.Waves.LeaseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.LeaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Waves.LeaseMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Lease transaction
     * </pre>
     *
     * Protobuf type {@code TW.Waves.Proto.LeaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Waves.LeaseMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Waves.Proto.LeaseMessage)
        wallet.core.jni.proto.Waves.LeaseMessageOrBuilder {
      // Construct using wallet.core.jni.proto.Waves.LeaseMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * amount
       * </pre>
       *
       * <code>int64 amount = 1;</code>
       * @return The amount.
       */
      @java.lang.Override
      public long getAmount() {
        return instance.getAmount();
      }
      /**
       * <pre>
       * amount
       * </pre>
       *
       * <code>int64 amount = 1;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(long value) {
        copyOnWrite();
        instance.setAmount(value);
        return this;
      }
      /**
       * <pre>
       * amount
       * </pre>
       *
       * <code>int64 amount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        copyOnWrite();
        instance.clearAmount();
        return this;
      }

      /**
       * <pre>
       * destination
       * </pre>
       *
       * <code>string to = 2;</code>
       * @return The to.
       */
      @java.lang.Override
      public java.lang.String getTo() {
        return instance.getTo();
      }
      /**
       * <pre>
       * destination
       * </pre>
       *
       * <code>string to = 2;</code>
       * @return The bytes for to.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getToBytes() {
        return instance.getToBytes();
      }
      /**
       * <pre>
       * destination
       * </pre>
       *
       * <code>string to = 2;</code>
       * @param value The to to set.
       * @return This builder for chaining.
       */
      public Builder setTo(
          java.lang.String value) {
        copyOnWrite();
        instance.setTo(value);
        return this;
      }
      /**
       * <pre>
       * destination
       * </pre>
       *
       * <code>string to = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTo() {
        copyOnWrite();
        instance.clearTo();
        return this;
      }
      /**
       * <pre>
       * destination
       * </pre>
       *
       * <code>string to = 2;</code>
       * @param value The bytes for to to set.
       * @return This builder for chaining.
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setToBytes(value);
        return this;
      }

      /**
       * <pre>
       * minimum 0.001 Waves (100000 Wavelets) for now
       * </pre>
       *
       * <code>int64 fee = 3;</code>
       * @return The fee.
       */
      @java.lang.Override
      public long getFee() {
        return instance.getFee();
      }
      /**
       * <pre>
       * minimum 0.001 Waves (100000 Wavelets) for now
       * </pre>
       *
       * <code>int64 fee = 3;</code>
       * @param value The fee to set.
       * @return This builder for chaining.
       */
      public Builder setFee(long value) {
        copyOnWrite();
        instance.setFee(value);
        return this;
      }
      /**
       * <pre>
       * minimum 0.001 Waves (100000 Wavelets) for now
       * </pre>
       *
       * <code>int64 fee = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFee() {
        copyOnWrite();
        instance.clearFee();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Waves.Proto.LeaseMessage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Waves.LeaseMessage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "amount_",
              "to_",
              "fee_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0002\u0002\u0208" +
                "\u0003\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Waves.LeaseMessage> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Waves.LeaseMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Waves.LeaseMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Waves.Proto.LeaseMessage)
    private static final wallet.core.jni.proto.Waves.LeaseMessage DEFAULT_INSTANCE;
    static {
      LeaseMessage defaultInstance = new LeaseMessage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LeaseMessage.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Waves.LeaseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LeaseMessage> PARSER;

    public static com.google.protobuf.Parser<LeaseMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CancelLeaseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Waves.Proto.CancelLeaseMessage)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Lease ID to cancel
     * </pre>
     *
     * <code>string lease_id = 1;</code>
     * @return The leaseId.
     */
    java.lang.String getLeaseId();
    /**
     * <pre>
     * Lease ID to cancel
     * </pre>
     *
     * <code>string lease_id = 1;</code>
     * @return The bytes for leaseId.
     */
    com.google.protobuf.ByteString
        getLeaseIdBytes();

    /**
     * <pre>
     * Fee used
     * </pre>
     *
     * <code>int64 fee = 2;</code>
     * @return The fee.
     */
    long getFee();
  }
  /**
   * <pre>
   * Cancel Lease transaction
   * </pre>
   *
   * Protobuf type {@code TW.Waves.Proto.CancelLeaseMessage}
   */
  public  static final class CancelLeaseMessage extends
      com.google.protobuf.GeneratedMessageLite<
          CancelLeaseMessage, CancelLeaseMessage.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Waves.Proto.CancelLeaseMessage)
      CancelLeaseMessageOrBuilder {
    private CancelLeaseMessage() {
      leaseId_ = "";
    }
    public static final int LEASE_ID_FIELD_NUMBER = 1;
    private java.lang.String leaseId_;
    /**
     * <pre>
     * Lease ID to cancel
     * </pre>
     *
     * <code>string lease_id = 1;</code>
     * @return The leaseId.
     */
    @java.lang.Override
    public java.lang.String getLeaseId() {
      return leaseId_;
    }
    /**
     * <pre>
     * Lease ID to cancel
     * </pre>
     *
     * <code>string lease_id = 1;</code>
     * @return The bytes for leaseId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeaseIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(leaseId_);
    }
    /**
     * <pre>
     * Lease ID to cancel
     * </pre>
     *
     * <code>string lease_id = 1;</code>
     * @param value The leaseId to set.
     */
    private void setLeaseId(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      leaseId_ = value;
    }
    /**
     * <pre>
     * Lease ID to cancel
     * </pre>
     *
     * <code>string lease_id = 1;</code>
     */
    private void clearLeaseId() {
      
      leaseId_ = getDefaultInstance().getLeaseId();
    }
    /**
     * <pre>
     * Lease ID to cancel
     * </pre>
     *
     * <code>string lease_id = 1;</code>
     * @param value The bytes for leaseId to set.
     */
    private void setLeaseIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      leaseId_ = value.toStringUtf8();
      
    }

    public static final int FEE_FIELD_NUMBER = 2;
    private long fee_;
    /**
     * <pre>
     * Fee used
     * </pre>
     *
     * <code>int64 fee = 2;</code>
     * @return The fee.
     */
    @java.lang.Override
    public long getFee() {
      return fee_;
    }
    /**
     * <pre>
     * Fee used
     * </pre>
     *
     * <code>int64 fee = 2;</code>
     * @param value The fee to set.
     */
    private void setFee(long value) {
      
      fee_ = value;
    }
    /**
     * <pre>
     * Fee used
     * </pre>
     *
     * <code>int64 fee = 2;</code>
     */
    private void clearFee() {
      
      fee_ = 0L;
    }

    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.CancelLeaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Waves.CancelLeaseMessage prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Cancel Lease transaction
     * </pre>
     *
     * Protobuf type {@code TW.Waves.Proto.CancelLeaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Waves.CancelLeaseMessage, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Waves.Proto.CancelLeaseMessage)
        wallet.core.jni.proto.Waves.CancelLeaseMessageOrBuilder {
      // Construct using wallet.core.jni.proto.Waves.CancelLeaseMessage.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Lease ID to cancel
       * </pre>
       *
       * <code>string lease_id = 1;</code>
       * @return The leaseId.
       */
      @java.lang.Override
      public java.lang.String getLeaseId() {
        return instance.getLeaseId();
      }
      /**
       * <pre>
       * Lease ID to cancel
       * </pre>
       *
       * <code>string lease_id = 1;</code>
       * @return The bytes for leaseId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getLeaseIdBytes() {
        return instance.getLeaseIdBytes();
      }
      /**
       * <pre>
       * Lease ID to cancel
       * </pre>
       *
       * <code>string lease_id = 1;</code>
       * @param value The leaseId to set.
       * @return This builder for chaining.
       */
      public Builder setLeaseId(
          java.lang.String value) {
        copyOnWrite();
        instance.setLeaseId(value);
        return this;
      }
      /**
       * <pre>
       * Lease ID to cancel
       * </pre>
       *
       * <code>string lease_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaseId() {
        copyOnWrite();
        instance.clearLeaseId();
        return this;
      }
      /**
       * <pre>
       * Lease ID to cancel
       * </pre>
       *
       * <code>string lease_id = 1;</code>
       * @param value The bytes for leaseId to set.
       * @return This builder for chaining.
       */
      public Builder setLeaseIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLeaseIdBytes(value);
        return this;
      }

      /**
       * <pre>
       * Fee used
       * </pre>
       *
       * <code>int64 fee = 2;</code>
       * @return The fee.
       */
      @java.lang.Override
      public long getFee() {
        return instance.getFee();
      }
      /**
       * <pre>
       * Fee used
       * </pre>
       *
       * <code>int64 fee = 2;</code>
       * @param value The fee to set.
       * @return This builder for chaining.
       */
      public Builder setFee(long value) {
        copyOnWrite();
        instance.setFee(value);
        return this;
      }
      /**
       * <pre>
       * Fee used
       * </pre>
       *
       * <code>int64 fee = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFee() {
        copyOnWrite();
        instance.clearFee();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Waves.Proto.CancelLeaseMessage)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Waves.CancelLeaseMessage();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "leaseId_",
              "fee_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0002" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Waves.CancelLeaseMessage> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Waves.CancelLeaseMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Waves.CancelLeaseMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Waves.Proto.CancelLeaseMessage)
    private static final wallet.core.jni.proto.Waves.CancelLeaseMessage DEFAULT_INSTANCE;
    static {
      CancelLeaseMessage defaultInstance = new CancelLeaseMessage();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CancelLeaseMessage.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Waves.CancelLeaseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CancelLeaseMessage> PARSER;

    public static com.google.protobuf.Parser<CancelLeaseMessage> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SigningInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Waves.Proto.SigningInput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * in millis
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 2;</code>
     * @return The privateKey.
     */
    com.google.protobuf.ByteString getPrivateKey();

    /**
     * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
     * @return Whether the transferMessage field is set.
     */
    boolean hasTransferMessage();
    /**
     * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
     * @return The transferMessage.
     */
    wallet.core.jni.proto.Waves.TransferMessage getTransferMessage();

    /**
     * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
     * @return Whether the leaseMessage field is set.
     */
    boolean hasLeaseMessage();
    /**
     * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
     * @return The leaseMessage.
     */
    wallet.core.jni.proto.Waves.LeaseMessage getLeaseMessage();

    /**
     * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
     * @return Whether the cancelLeaseMessage field is set.
     */
    boolean hasCancelLeaseMessage();
    /**
     * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
     * @return The cancelLeaseMessage.
     */
    wallet.core.jni.proto.Waves.CancelLeaseMessage getCancelLeaseMessage();

    public wallet.core.jni.proto.Waves.SigningInput.MessageOneofCase getMessageOneofCase();
  }
  /**
   * <pre>
   * Input data necessary to create a signed transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Waves.Proto.SigningInput}
   */
  public  static final class SigningInput extends
      com.google.protobuf.GeneratedMessageLite<
          SigningInput, SigningInput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Waves.Proto.SigningInput)
      SigningInputOrBuilder {
    private SigningInput() {
      privateKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int messageOneofCase_ = 0;
    private java.lang.Object messageOneof_;
    public enum MessageOneofCase {
      TRANSFER_MESSAGE(3),
      LEASE_MESSAGE(4),
      CANCEL_LEASE_MESSAGE(5),
      MESSAGEONEOF_NOT_SET(0);
      private final int value;
      private MessageOneofCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static MessageOneofCase forNumber(int value) {
        switch (value) {
          case 3: return TRANSFER_MESSAGE;
          case 4: return LEASE_MESSAGE;
          case 5: return CANCEL_LEASE_MESSAGE;
          case 0: return MESSAGEONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    @java.lang.Override
    public MessageOneofCase
    getMessageOneofCase() {
      return MessageOneofCase.forNumber(
          messageOneofCase_);
    }

    private void clearMessageOneof() {
      messageOneofCase_ = 0;
      messageOneof_ = null;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <pre>
     * in millis
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * in millis
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <pre>
     * in millis
     * </pre>
     *
     * <code>int64 timestamp = 1;</code>
     */
    private void clearTimestamp() {
      
      timestamp_ = 0L;
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString privateKey_;
    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 2;</code>
     * @return The privateKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrivateKey() {
      return privateKey_;
    }
    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 2;</code>
     * @param value The privateKey to set.
     */
    private void setPrivateKey(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      privateKey_ = value;
    }
    /**
     * <pre>
     * The secret private key used for signing (32 bytes).
     * </pre>
     *
     * <code>bytes private_key = 2;</code>
     */
    private void clearPrivateKey() {
      
      privateKey_ = getDefaultInstance().getPrivateKey();
    }

    public static final int TRANSFER_MESSAGE_FIELD_NUMBER = 3;
    /**
     * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
     */
    @java.lang.Override
    public boolean hasTransferMessage() {
      return messageOneofCase_ == 3;
    }
    /**
     * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
     */
    @java.lang.Override
    public wallet.core.jni.proto.Waves.TransferMessage getTransferMessage() {
      if (messageOneofCase_ == 3) {
         return (wallet.core.jni.proto.Waves.TransferMessage) messageOneof_;
      }
      return wallet.core.jni.proto.Waves.TransferMessage.getDefaultInstance();
    }
    /**
     * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
     */
    private void setTransferMessage(wallet.core.jni.proto.Waves.TransferMessage value) {
      value.getClass();
  messageOneof_ = value;
      messageOneofCase_ = 3;
    }
    /**
     * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
     */
    private void mergeTransferMessage(wallet.core.jni.proto.Waves.TransferMessage value) {
      value.getClass();
  if (messageOneofCase_ == 3 &&
          messageOneof_ != wallet.core.jni.proto.Waves.TransferMessage.getDefaultInstance()) {
        messageOneof_ = wallet.core.jni.proto.Waves.TransferMessage.newBuilder((wallet.core.jni.proto.Waves.TransferMessage) messageOneof_)
            .mergeFrom(value).buildPartial();
      } else {
        messageOneof_ = value;
      }
      messageOneofCase_ = 3;
    }
    /**
     * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
     */
    private void clearTransferMessage() {
      if (messageOneofCase_ == 3) {
        messageOneofCase_ = 0;
        messageOneof_ = null;
      }
    }

    public static final int LEASE_MESSAGE_FIELD_NUMBER = 4;
    /**
     * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
     */
    @java.lang.Override
    public boolean hasLeaseMessage() {
      return messageOneofCase_ == 4;
    }
    /**
     * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
     */
    @java.lang.Override
    public wallet.core.jni.proto.Waves.LeaseMessage getLeaseMessage() {
      if (messageOneofCase_ == 4) {
         return (wallet.core.jni.proto.Waves.LeaseMessage) messageOneof_;
      }
      return wallet.core.jni.proto.Waves.LeaseMessage.getDefaultInstance();
    }
    /**
     * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
     */
    private void setLeaseMessage(wallet.core.jni.proto.Waves.LeaseMessage value) {
      value.getClass();
  messageOneof_ = value;
      messageOneofCase_ = 4;
    }
    /**
     * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
     */
    private void mergeLeaseMessage(wallet.core.jni.proto.Waves.LeaseMessage value) {
      value.getClass();
  if (messageOneofCase_ == 4 &&
          messageOneof_ != wallet.core.jni.proto.Waves.LeaseMessage.getDefaultInstance()) {
        messageOneof_ = wallet.core.jni.proto.Waves.LeaseMessage.newBuilder((wallet.core.jni.proto.Waves.LeaseMessage) messageOneof_)
            .mergeFrom(value).buildPartial();
      } else {
        messageOneof_ = value;
      }
      messageOneofCase_ = 4;
    }
    /**
     * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
     */
    private void clearLeaseMessage() {
      if (messageOneofCase_ == 4) {
        messageOneofCase_ = 0;
        messageOneof_ = null;
      }
    }

    public static final int CANCEL_LEASE_MESSAGE_FIELD_NUMBER = 5;
    /**
     * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
     */
    @java.lang.Override
    public boolean hasCancelLeaseMessage() {
      return messageOneofCase_ == 5;
    }
    /**
     * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
     */
    @java.lang.Override
    public wallet.core.jni.proto.Waves.CancelLeaseMessage getCancelLeaseMessage() {
      if (messageOneofCase_ == 5) {
         return (wallet.core.jni.proto.Waves.CancelLeaseMessage) messageOneof_;
      }
      return wallet.core.jni.proto.Waves.CancelLeaseMessage.getDefaultInstance();
    }
    /**
     * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
     */
    private void setCancelLeaseMessage(wallet.core.jni.proto.Waves.CancelLeaseMessage value) {
      value.getClass();
  messageOneof_ = value;
      messageOneofCase_ = 5;
    }
    /**
     * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
     */
    private void mergeCancelLeaseMessage(wallet.core.jni.proto.Waves.CancelLeaseMessage value) {
      value.getClass();
  if (messageOneofCase_ == 5 &&
          messageOneof_ != wallet.core.jni.proto.Waves.CancelLeaseMessage.getDefaultInstance()) {
        messageOneof_ = wallet.core.jni.proto.Waves.CancelLeaseMessage.newBuilder((wallet.core.jni.proto.Waves.CancelLeaseMessage) messageOneof_)
            .mergeFrom(value).buildPartial();
      } else {
        messageOneof_ = value;
      }
      messageOneofCase_ = 5;
    }
    /**
     * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
     */
    private void clearCancelLeaseMessage() {
      if (messageOneofCase_ == 5) {
        messageOneofCase_ = 0;
        messageOneof_ = null;
      }
    }

    public static wallet.core.jni.proto.Waves.SigningInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.SigningInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Waves.SigningInput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Input data necessary to create a signed transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Waves.Proto.SigningInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Waves.SigningInput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Waves.Proto.SigningInput)
        wallet.core.jni.proto.Waves.SigningInputOrBuilder {
      // Construct using wallet.core.jni.proto.Waves.SigningInput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @java.lang.Override
      public MessageOneofCase
          getMessageOneofCase() {
        return instance.getMessageOneofCase();
      }

      public Builder clearMessageOneof() {
        copyOnWrite();
        instance.clearMessageOneof();
        return this;
      }


      /**
       * <pre>
       * in millis
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * in millis
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * in millis
       * </pre>
       *
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <pre>
       * The secret private key used for signing (32 bytes).
       * </pre>
       *
       * <code>bytes private_key = 2;</code>
       * @return The privateKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPrivateKey() {
        return instance.getPrivateKey();
      }
      /**
       * <pre>
       * The secret private key used for signing (32 bytes).
       * </pre>
       *
       * <code>bytes private_key = 2;</code>
       * @param value The privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPrivateKey(value);
        return this;
      }
      /**
       * <pre>
       * The secret private key used for signing (32 bytes).
       * </pre>
       *
       * <code>bytes private_key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKey() {
        copyOnWrite();
        instance.clearPrivateKey();
        return this;
      }

      /**
       * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
       */
      @java.lang.Override
      public boolean hasTransferMessage() {
        return instance.hasTransferMessage();
      }
      /**
       * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
       */
      @java.lang.Override
      public wallet.core.jni.proto.Waves.TransferMessage getTransferMessage() {
        return instance.getTransferMessage();
      }
      /**
       * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
       */
      public Builder setTransferMessage(wallet.core.jni.proto.Waves.TransferMessage value) {
        copyOnWrite();
        instance.setTransferMessage(value);
        return this;
      }
      /**
       * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
       */
      public Builder setTransferMessage(
          wallet.core.jni.proto.Waves.TransferMessage.Builder builderForValue) {
        copyOnWrite();
        instance.setTransferMessage(builderForValue.build());
        return this;
      }
      /**
       * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
       */
      public Builder mergeTransferMessage(wallet.core.jni.proto.Waves.TransferMessage value) {
        copyOnWrite();
        instance.mergeTransferMessage(value);
        return this;
      }
      /**
       * <code>.TW.Waves.Proto.TransferMessage transfer_message = 3;</code>
       */
      public Builder clearTransferMessage() {
        copyOnWrite();
        instance.clearTransferMessage();
        return this;
      }

      /**
       * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
       */
      @java.lang.Override
      public boolean hasLeaseMessage() {
        return instance.hasLeaseMessage();
      }
      /**
       * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
       */
      @java.lang.Override
      public wallet.core.jni.proto.Waves.LeaseMessage getLeaseMessage() {
        return instance.getLeaseMessage();
      }
      /**
       * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
       */
      public Builder setLeaseMessage(wallet.core.jni.proto.Waves.LeaseMessage value) {
        copyOnWrite();
        instance.setLeaseMessage(value);
        return this;
      }
      /**
       * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
       */
      public Builder setLeaseMessage(
          wallet.core.jni.proto.Waves.LeaseMessage.Builder builderForValue) {
        copyOnWrite();
        instance.setLeaseMessage(builderForValue.build());
        return this;
      }
      /**
       * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
       */
      public Builder mergeLeaseMessage(wallet.core.jni.proto.Waves.LeaseMessage value) {
        copyOnWrite();
        instance.mergeLeaseMessage(value);
        return this;
      }
      /**
       * <code>.TW.Waves.Proto.LeaseMessage lease_message = 4;</code>
       */
      public Builder clearLeaseMessage() {
        copyOnWrite();
        instance.clearLeaseMessage();
        return this;
      }

      /**
       * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
       */
      @java.lang.Override
      public boolean hasCancelLeaseMessage() {
        return instance.hasCancelLeaseMessage();
      }
      /**
       * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
       */
      @java.lang.Override
      public wallet.core.jni.proto.Waves.CancelLeaseMessage getCancelLeaseMessage() {
        return instance.getCancelLeaseMessage();
      }
      /**
       * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
       */
      public Builder setCancelLeaseMessage(wallet.core.jni.proto.Waves.CancelLeaseMessage value) {
        copyOnWrite();
        instance.setCancelLeaseMessage(value);
        return this;
      }
      /**
       * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
       */
      public Builder setCancelLeaseMessage(
          wallet.core.jni.proto.Waves.CancelLeaseMessage.Builder builderForValue) {
        copyOnWrite();
        instance.setCancelLeaseMessage(builderForValue.build());
        return this;
      }
      /**
       * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
       */
      public Builder mergeCancelLeaseMessage(wallet.core.jni.proto.Waves.CancelLeaseMessage value) {
        copyOnWrite();
        instance.mergeCancelLeaseMessage(value);
        return this;
      }
      /**
       * <code>.TW.Waves.Proto.CancelLeaseMessage cancel_lease_message = 5;</code>
       */
      public Builder clearCancelLeaseMessage() {
        copyOnWrite();
        instance.clearCancelLeaseMessage();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Waves.Proto.SigningInput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Waves.SigningInput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "messageOneof_",
              "messageOneofCase_",
              "timestamp_",
              "privateKey_",
              wallet.core.jni.proto.Waves.TransferMessage.class,
              wallet.core.jni.proto.Waves.LeaseMessage.class,
              wallet.core.jni.proto.Waves.CancelLeaseMessage.class,
            };
            java.lang.String info =
                "\u0000\u0005\u0001\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0002\u0002\n" +
                "\u0003<\u0000\u0004<\u0000\u0005<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Waves.SigningInput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Waves.SigningInput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Waves.SigningInput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Waves.Proto.SigningInput)
    private static final wallet.core.jni.proto.Waves.SigningInput DEFAULT_INSTANCE;
    static {
      SigningInput defaultInstance = new SigningInput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SigningInput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Waves.SigningInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningInput> PARSER;

    public static com.google.protobuf.Parser<SigningInput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SigningOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TW.Waves.Proto.SigningOutput)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * signature data
     * </pre>
     *
     * <code>bytes signature = 1;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <pre>
     * transaction in JSON format
     * </pre>
     *
     * <code>string json = 2;</code>
     * @return The json.
     */
    java.lang.String getJson();
    /**
     * <pre>
     * transaction in JSON format
     * </pre>
     *
     * <code>string json = 2;</code>
     * @return The bytes for json.
     */
    com.google.protobuf.ByteString
        getJsonBytes();
  }
  /**
   * <pre>
   * Result containing the signed and encoded transaction.
   * </pre>
   *
   * Protobuf type {@code TW.Waves.Proto.SigningOutput}
   */
  public  static final class SigningOutput extends
      com.google.protobuf.GeneratedMessageLite<
          SigningOutput, SigningOutput.Builder> implements
      // @@protoc_insertion_point(message_implements:TW.Waves.Proto.SigningOutput)
      SigningOutputOrBuilder {
    private SigningOutput() {
      signature_ = com.google.protobuf.ByteString.EMPTY;
      json_ = "";
    }
    public static final int SIGNATURE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString signature_;
    /**
     * <pre>
     * signature data
     * </pre>
     *
     * <code>bytes signature = 1;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <pre>
     * signature data
     * </pre>
     *
     * <code>bytes signature = 1;</code>
     * @param value The signature to set.
     */
    private void setSignature(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      signature_ = value;
    }
    /**
     * <pre>
     * signature data
     * </pre>
     *
     * <code>bytes signature = 1;</code>
     */
    private void clearSignature() {
      
      signature_ = getDefaultInstance().getSignature();
    }

    public static final int JSON_FIELD_NUMBER = 2;
    private java.lang.String json_;
    /**
     * <pre>
     * transaction in JSON format
     * </pre>
     *
     * <code>string json = 2;</code>
     * @return The json.
     */
    @java.lang.Override
    public java.lang.String getJson() {
      return json_;
    }
    /**
     * <pre>
     * transaction in JSON format
     * </pre>
     *
     * <code>string json = 2;</code>
     * @return The bytes for json.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJsonBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(json_);
    }
    /**
     * <pre>
     * transaction in JSON format
     * </pre>
     *
     * <code>string json = 2;</code>
     * @param value The json to set.
     */
    private void setJson(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      json_ = value;
    }
    /**
     * <pre>
     * transaction in JSON format
     * </pre>
     *
     * <code>string json = 2;</code>
     */
    private void clearJson() {
      
      json_ = getDefaultInstance().getJson();
    }
    /**
     * <pre>
     * transaction in JSON format
     * </pre>
     *
     * <code>string json = 2;</code>
     * @param value The bytes for json to set.
     */
    private void setJsonBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      json_ = value.toStringUtf8();
      
    }

    public static wallet.core.jni.proto.Waves.SigningOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static wallet.core.jni.proto.Waves.SigningOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(wallet.core.jni.proto.Waves.SigningOutput prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * <pre>
     * Result containing the signed and encoded transaction.
     * </pre>
     *
     * Protobuf type {@code TW.Waves.Proto.SigningOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          wallet.core.jni.proto.Waves.SigningOutput, Builder> implements
        // @@protoc_insertion_point(builder_implements:TW.Waves.Proto.SigningOutput)
        wallet.core.jni.proto.Waves.SigningOutputOrBuilder {
      // Construct using wallet.core.jni.proto.Waves.SigningOutput.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * signature data
       * </pre>
       *
       * <code>bytes signature = 1;</code>
       * @return The signature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSignature() {
        return instance.getSignature();
      }
      /**
       * <pre>
       * signature data
       * </pre>
       *
       * <code>bytes signature = 1;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSignature(value);
        return this;
      }
      /**
       * <pre>
       * signature data
       * </pre>
       *
       * <code>bytes signature = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        copyOnWrite();
        instance.clearSignature();
        return this;
      }

      /**
       * <pre>
       * transaction in JSON format
       * </pre>
       *
       * <code>string json = 2;</code>
       * @return The json.
       */
      @java.lang.Override
      public java.lang.String getJson() {
        return instance.getJson();
      }
      /**
       * <pre>
       * transaction in JSON format
       * </pre>
       *
       * <code>string json = 2;</code>
       * @return The bytes for json.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getJsonBytes() {
        return instance.getJsonBytes();
      }
      /**
       * <pre>
       * transaction in JSON format
       * </pre>
       *
       * <code>string json = 2;</code>
       * @param value The json to set.
       * @return This builder for chaining.
       */
      public Builder setJson(
          java.lang.String value) {
        copyOnWrite();
        instance.setJson(value);
        return this;
      }
      /**
       * <pre>
       * transaction in JSON format
       * </pre>
       *
       * <code>string json = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearJson() {
        copyOnWrite();
        instance.clearJson();
        return this;
      }
      /**
       * <pre>
       * transaction in JSON format
       * </pre>
       *
       * <code>string json = 2;</code>
       * @param value The bytes for json to set.
       * @return This builder for chaining.
       */
      public Builder setJsonBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setJsonBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TW.Waves.Proto.SigningOutput)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new wallet.core.jni.proto.Waves.SigningOutput();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "signature_",
              "json_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\n\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<wallet.core.jni.proto.Waves.SigningOutput> parser = PARSER;
          if (parser == null) {
            synchronized (wallet.core.jni.proto.Waves.SigningOutput.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<wallet.core.jni.proto.Waves.SigningOutput>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:TW.Waves.Proto.SigningOutput)
    private static final wallet.core.jni.proto.Waves.SigningOutput DEFAULT_INSTANCE;
    static {
      SigningOutput defaultInstance = new SigningOutput();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SigningOutput.class, defaultInstance);
    }

    public static wallet.core.jni.proto.Waves.SigningOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SigningOutput> PARSER;

    public static com.google.protobuf.Parser<SigningOutput> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
