#!/bin/bash

python3 tools/apply_environment.py "coldwallet_testnet"
./tools/generate-files
pushd android
./gradlew clean
./gradlew assembleRelease --stacktrace
cp trustwalletcore/build/outputs/aar/trustwalletcore-release.aar ../build/walletcore-coldwallet-testnet.aar
popd
echo "Build Android Success"