#!/bin/bash

python3 tools/apply_environment.py "default_mainnet"
./tools/generate-files
pushd android
./gradlew clean
./gradlew assembleRelease --stacktrace
cp trustwalletcore/build/outputs/aar/trustwalletcore-release.aar ../build/walletcore-viawallet-mainnet.aar
popd
echo "Build Android Success"
