#!/bin/bash
#
# This script builds the Android release package.

set -e

source $(dirname $0)/library
version=$(wc_read_version)

pushd android
./gradlew clean
./gradlew assembleRelease --stacktrace
cp trustwalletcore/build/outputs/aar/trustwalletcore-release.aar ../build/trustwalletcore.aar
popd

echo "Android build success"
