#!/bin/bash
cp ../../registry/viawallet/registry.json ../../registry.json
cd ../../android
./gradlew clean
./gradlew assembleRelease --stacktrace
cp trustwalletcore/build/outputs/aar/trustwalletcore-release.aar ../build/trustwalletcore-viawallet.aar
cd ..
echo "Android build success"
